import { Category, Language, UITranslationKeys } from './types';

export const UI_TRANSLATIONS: Record<Language, Record<UITranslationKeys, string>> = {
  en: {
    appName: 'FeelSync',
    categories: 'Categories',
    exploreWisdom: 'Explore wisdom across different themes',
    moodAnalysis: 'AI Mood Analysis',
    moodPlaceholder: 'How do you feel? Talk to me...',
    analyze: 'Analyze & Generate',
    dailyQuote: 'Daily Quote',
    trending: 'Trending Now',
    randomQuote: 'Random Quote',
    copied: 'Copied successfully',
    generating: 'Generating wisdom...',
    analyzing: 'Analyzing your mood...',
    noQuotes: 'No quotes found',
    favorites: 'Favorites',
    back: 'Back',
    generateMore: 'Generate More',
    detectedEmotion: 'Detected Emotion',
    personalizedForYou: 'Personalized for you',
    setAsWallpaper: 'Set as Wallpaper',
    homeScreen: 'Home Screen',
    lockScreen: 'Lock Screen',
    downloading: 'Preparing wallpaper...',
    wallpaperSaved: 'Wallpaper saved to gallery',
    streak: 'Day Streak',
    offlineMode: 'Offline Mode',
    notifications: 'Notifications',
    enableNotifications: 'Enable Daily Reminders',
    notificationsEnabledMessage: 'Notifications enabled!',
    notificationsDeniedMessage: 'Please enable notifications in settings',
    newQuoteAvailable: 'New daily quote available!',
    includeReligious: 'Include Religious Wisdom',
    religiousWisdom: 'Sacred Wisdom',
    dailyQuoteNotification: 'Your personalized quote for today is ready...',
    selectLanguage: 'Select Your Language',
    premiumCustomization: 'Premium Customization',
    alignment: 'Alignment',
    position: 'Position',
    typography: 'Typography',
    styleAtmosphere: 'Style & Atmosphere',
    styleMinimal: 'Minimal',
    styleNature: 'Nature',
    styleCalm: 'Calm',
    styleWarm: 'Warm',
    styleDeep: 'Deep',
    styleLuxury: 'Luxury',
    styleCreative: 'Creative',
    fontModern: 'Modern',
    fontPremium: 'Premium',
    fontTech: 'Tech',
    fontBold: 'Bold',
    fontElegant: 'Elegant',
    chooseLanguage: 'Choose Your Language',
    selectLanguageSub: 'Select your preferred language to continue',
    notificationMood: 'A little something for your mood...',
    notificationFavorites: 'Ready for more wisdom like your favorites?',
    copyText: 'Copy Quote',
  },
  fr: {
    appName: 'FeelSync',
    categories: 'Catégories',
    exploreWisdom: 'Explorez la sagesse à travers différents thèmes',
    moodAnalysis: 'Analyse de l\'humeur par l\'IA',
    moodPlaceholder: 'Comment vous sentez-vous ? Parlez-moi...',
    analyze: 'Analyser et Générer',
    dailyQuote: 'Citation du jour',
    trending: 'Tendances actuelles',
    randomQuote: 'Citation aléatoire',
    copied: 'Copié avec succès',
    generating: 'Génération de sagesse...',
    analyzing: 'Analyse de votre humeur...',
    noQuotes: 'Aucune citation trouvée',
    favorites: 'Favoris',
    back: 'Retour',
    generateMore: 'Générer plus',
    detectedEmotion: 'Émotion détectée',
    personalizedForYou: 'Personnalisé pour vous',
    setAsWallpaper: 'Définir comme fond d\'écran',
    homeScreen: 'Écran d\'accueil',
    lockScreen: 'Écran de verrouillage',
    downloading: 'Préparation du fond d\'écran...',
    wallpaperSaved: 'Fond d\'écran enregistré dans la galerie',
    streak: 'Série de jours',
    offlineMode: 'Mode hors ligne',
    notifications: 'Notifications',
    enableNotifications: 'Activer les rappels quotidiens',
    notificationsEnabledMessage: 'Notifications activées !',
    notificationsDeniedMessage: 'Veuillez activer les notifications dans les paramètres',
    newQuoteAvailable: 'Nouvelle citation du jour disponible !',
    includeReligious: 'Inclure la sagesse religieuse',
    religiousWisdom: 'Sagesse Sacrée',
    dailyQuoteNotification: 'Votre citation personnalisée du jour est prête...',
    selectLanguage: 'Choisissez votre langue',
    premiumCustomization: 'Personnalisation Premium',
    alignment: 'Alignement',
    position: 'Position',
    typography: 'Typographie',
    styleAtmosphere: 'Style et Atmosphère',
    styleMinimal: 'Minimal',
    styleNature: 'Nature',
    styleCalm: 'Calme',
    styleWarm: 'Chaud',
    styleDeep: 'Profond',
    styleLuxury: 'Luxe',
    styleCreative: 'Créatif',
    fontModern: 'Moderne',
    fontPremium: 'Premium',
    fontTech: 'Tech',
    fontBold: 'Gras',
    fontElegant: 'Élégant',
    chooseLanguage: 'Choisissez votre langue',
    selectLanguageSub: 'Sélectionnez votre langue préférée pour continuer',
    notificationMood: 'Un petit quelque chose pour votre humeur...',
    notificationFavorites: 'Prêt pour plus de sagesse comme vos favoris ?',
    copyText: 'Copier la citation',
  },
  es: {
    appName: 'FeelSync',
    categories: 'Categorías',
    exploreWisdom: 'Explora la sabiduría en diferentes temas',
    moodAnalysis: 'Análisis de ánimo IA',
    moodPlaceholder: '¿Cómo te sientes? Cuéntame...',
    analyze: 'Analizar y Generar',
    dailyQuote: 'Cita Diaria',
    trending: 'Tendencias',
    randomQuote: 'Cita Aleatoria',
    copied: 'Copiado con éxito',
    generating: 'Generando sabiduría...',
    analyzing: 'Analizando tu ánimo...',
    noQuotes: 'No se encontraron citas',
    favorites: 'Favoritos',
    back: 'Volver',
    generateMore: 'Generar más',
    detectedEmotion: 'Emoción detectada',
    personalizedForYou: 'Personalizado para ti',
    setAsWallpaper: 'Establecer como fondo',
    homeScreen: 'Pantalla de inicio',
    lockScreen: 'Pantalla de bloqueo',
    downloading: 'Preparando fondo...',
    wallpaperSaved: 'Fondo guardado en la galería',
    streak: 'Racha de días',
    offlineMode: 'Modo fuera de línea',
    notifications: 'Notificaciones',
    enableNotifications: 'Activar recordatorios diarios',
    notificationsEnabledMessage: '¡Notificaciones activadas!',
    notificationsDeniedMessage: 'Por favor, activa las notificaciones en la configuración',
    newQuoteAvailable: '¡Nueva cita diaria disponible!',
    includeReligious: 'Incluir sabiduría religiosa',
    religiousWisdom: 'Sabiduría Sagrada',
    dailyQuoteNotification: 'Tu cita personalizada de hoy está lista...',
    selectLanguage: 'Selecciona tu idioma',
    premiumCustomization: 'Personalización Premium',
    alignment: 'Alineación',
    position: 'Posición',
    typography: 'Tipografía',
    styleAtmosphere: 'Estilo y Atmósfera',
    styleMinimal: 'Minimalista',
    styleNature: 'Naturaleza',
    styleCalm: 'Calma',
    styleWarm: 'Cálido',
    styleDeep: 'Profundo',
    styleLuxury: 'Lujo',
    styleCreative: 'Creativo',
    fontModern: 'Moderno',
    fontPremium: 'Premium',
    fontTech: 'Tech',
    fontBold: 'Negrita',
    fontElegant: 'Elegante',
    chooseLanguage: 'Elige tu idioma',
    selectLanguageSub: 'Selecciona tu idioma preferido para continuar',
    notificationMood: 'Algo para tu estado de ánimo...',
    notificationFavorites: '¿Listo para más sabiduría como tus favoritos?',
    copyText: 'Copiar cita',
  },
  de: {
    appName: 'FeelSync',
    categories: 'Kategorien',
    exploreWisdom: 'Entdecke Weisheit in verschiedenen Themen',
    moodAnalysis: 'KI-Stimmungsanalyse',
    moodPlaceholder: 'Wie fühlst du dich? Sprich mit mir...',
    analyze: 'Analysieren & Generieren',
    dailyQuote: 'Tägliches Zitat',
    trending: 'Angesagt',
    randomQuote: 'Zufälliges Zitat',
    copied: 'Erfolgreich kopiert',
    generating: 'Weisheit wird generiert...',
    analyzing: 'Stimmung wird analysiert...',
    noQuotes: 'Keine Zitate gefunden',
    favorites: 'Favoriten',
    back: 'Zurück',
    generateMore: 'Mehr generieren',
    detectedEmotion: 'Erkannte Emotion',
    personalizedForYou: 'Personalisiert für dich',
    setAsWallpaper: 'Als Hintergrundbild festlegen',
    homeScreen: 'Startbildschirm',
    lockScreen: 'Sperrbildschirm',
    downloading: 'Hintergrundbild wird vorbereitet...',
    wallpaperSaved: 'Hintergrundbild in Galerie gespeichert',
    streak: 'Tages-Streak',
    offlineMode: 'Offline-Modus',
    notifications: 'Benachrichtigungen',
    enableNotifications: 'Tägliche Erinnerungen aktivieren',
    notificationsEnabledMessage: 'Benachrichtigungen aktiviert!',
    notificationsDeniedMessage: 'Bitte aktiviere die Benachrichtigungen in den Einstellungen',
    newQuoteAvailable: 'Neues tägliches Zitat verfügbar!',
    includeReligious: 'Religiöse Weisheit einbeziehen',
    religiousWisdom: 'Heilige Weisheit',
    dailyQuoteNotification: 'Dein personalisiertes Zitat für heute ist bereit...',
    selectLanguage: 'Wähle deine Sprache',
    premiumCustomization: 'Premium-Anpassung',
    alignment: 'Ausrichtung',
    position: 'Position',
    typography: 'Typografie',
    styleAtmosphere: 'Stil & Atmosphäre',
    styleMinimal: 'Minimal',
    styleNature: 'Natur',
    styleCalm: 'Ruhig',
    styleWarm: 'Warm',
    styleDeep: 'Tief',
    styleLuxury: 'Luxus',
    styleCreative: 'Kreativ',
    fontModern: 'Modern',
    fontPremium: 'Premium',
    fontTech: 'Tech',
    fontBold: 'Fett',
    fontElegant: 'Elegant',
    chooseLanguage: 'Wähle deine Sprache',
    selectLanguageSub: 'Wähle deine bevorzugte Sprache, um fortzufahren',
    notificationMood: 'Etwas für deine Stimmung...',
    notificationFavorites: 'Bereit für mehr Weisheit wie deine Favoriten?',
    copyText: 'Zitat kopieren',
  },
  pt: {
    appName: 'FeelSync',
    categories: 'Categorias',
    exploreWisdom: 'Explore a sabedoria em diferentes temas',
    moodAnalysis: 'Análise de Humor IA',
    moodPlaceholder: 'Como você se sente? Fale comigo...',
    analyze: 'Analisar e Gerar',
    dailyQuote: 'Citação Diária',
    trending: 'Tendências',
    randomQuote: 'Citação Aleatória',
    copied: 'Copiado com sucesso',
    generating: 'Gerando sabedoria...',
    analyzing: 'Analisando seu humor...',
    noQuotes: 'Nenhuma citação encontrada',
    favorites: 'Favoritos',
    back: 'Voltar',
    generateMore: 'Gerar mais',
    detectedEmotion: 'Emoção detectada',
    personalizedForYou: 'Personalizado para você',
    setAsWallpaper: 'Definir como papel de parede',
    homeScreen: 'Tela inicial',
    lockScreen: 'Tela de bloqueio',
    downloading: 'Preparando papel de parede...',
    wallpaperSaved: 'Papel de parede salvo na galeria',
    streak: 'Sequência de dias',
    offlineMode: 'Modo offline',
    notifications: 'Notificações',
    enableNotifications: 'Ativar lembretes diários',
    notificationsEnabledMessage: 'Notificações ativadas!',
    notificationsDeniedMessage: 'Por favor, ative as notificações nas configurações',
    newQuoteAvailable: 'Nova citação diária disponível!',
    includeReligious: 'Incluir sabedoria religiosa',
    religiousWisdom: 'Sabedoria Sagrada',
    dailyQuoteNotification: 'Sua citação personalizada de hoje está pronta...',
    selectLanguage: 'Selecione seu idioma',
    premiumCustomization: 'Personalização Premium',
    alignment: 'Alinhamento',
    position: 'Posição',
    typography: 'Tipografia',
    styleAtmosphere: 'Estilo e Atmosfera',
    styleMinimal: 'Minimalista',
    styleNature: 'Natureza',
    styleCalm: 'Calmo',
    styleWarm: 'Quente',
    styleDeep: 'Profundo',
    styleLuxury: 'Luxo',
    styleCreative: 'Criativo',
    fontModern: 'Moderno',
    fontPremium: 'Premium',
    fontTech: 'Tech',
    fontBold: 'Negrito',
    fontElegant: 'Elegante',
    chooseLanguage: 'Escolha seu idioma',
    selectLanguageSub: 'Selecione seu idioma preferido para continuar',
    notificationMood: 'Algo para o seu humor...',
    notificationFavorites: 'Pronto para mais sabedoria como seus favoritos?',
    copyText: 'Copiar citação',
  },
  hi: {
    appName: 'FeelSync',
    categories: 'श्रेणियाँ',
    exploreWisdom: 'विभिन्न विषयों में ज्ञान खोजें',
    moodAnalysis: 'AI मूड विश्लेषण',
    moodPlaceholder: 'आप कैसा महसूस कर रहे हैं? मुझसे बात करें...',
    analyze: 'विश्लेषण और उत्पन्न करें',
    dailyQuote: 'दैनिक विचार',
    trending: 'अभी ट्रेंडिंग',
    randomQuote: 'यादृच्छिक विचार',
    copied: 'सफलतापूर्वक कॉपी किया गया',
    generating: 'ज्ञान उत्पन्न किया जा रहा है...',
    analyzing: 'आपके मूड का विश्लेषण किया जा रहा है...',
    noQuotes: 'कोई विचार नहीं मिला',
    favorites: 'पसंदीदा',
    back: 'पीछे',
    generateMore: 'और उत्पन्न करें',
    detectedEmotion: 'पहचानी गई भावना',
    personalizedForYou: 'आपके लिए व्यक्तिगत',
    setAsWallpaper: 'वॉलपेपर के रूप में सेट करें',
    homeScreen: 'होम स्क्रीन',
    lockScreen: 'लॉक स्क्रीन',
    downloading: 'वॉलपेपर तैयार किया जा रहा है...',
    wallpaperSaved: 'वॉलपेपर गैलरी में सहेजा गया',
    streak: 'दिनों का सिलसिला',
    offlineMode: 'ऑफ़लाइन मोड',
    notifications: 'सूचनाएं',
    enableNotifications: 'दैनिक अनुस्मारक सक्षम करें',
    notificationsEnabledMessage: 'सूचनाएं सक्षम की गईं!',
    notificationsDeniedMessage: 'कृपया सेटिंग्स में सूचनाएं सक्षम करें',
    newQuoteAvailable: 'नया दैनिक विचार उपलब्ध है!',
    includeReligious: 'धार्मिक ज्ञान शामिल करें',
    religiousWisdom: 'पवित्र ज्ञान',
    dailyQuoteNotification: 'आज के लिए आपका व्यक्तिगत विचार तैयार है...',
    selectLanguage: 'अपनी भाषा चुनें',
    premiumCustomization: 'प्रीमियम अनुकूलन',
    alignment: 'संरेखण',
    position: 'स्थिति',
    typography: 'टाइपोग्राफी',
    styleAtmosphere: 'शैली और वातावरण',
    styleMinimal: 'न्यूनतम',
    styleNature: 'प्रकृति',
    styleCalm: 'शांत',
    styleWarm: 'गर्म',
    styleDeep: 'गहरा',
    styleLuxury: 'लक्जरी',
    styleCreative: 'रचनात्मक',
    fontModern: 'आधुनिक',
    fontPremium: 'प्रीमियम',
    fontTech: 'टेक',
    fontBold: 'बोल्ड',
    fontElegant: 'सुरुचिपूर्ण',
    chooseLanguage: 'अपनी भाषा चुनें',
    selectLanguageSub: 'जारी रखने के लिए अपनी पसंदीदा भाषा चुनें',
    notificationMood: 'आपके मूड के लिए कुछ खास...',
    notificationFavorites: 'क्या आप अपने पसंदीदा जैसे और ज्ञान के लिए तैयार हैं?',
    copyText: 'उद्धरण कॉपी करें',
  },
  ar: {
    appName: 'FeelSync',
    categories: 'الفئات',
    exploreWisdom: 'استكشف الحكمة عبر مواضيع مختلفة',
    moodAnalysis: 'تحليل الحالة المزاجية بالذكاء الاصطناعي',
    moodPlaceholder: 'كيف تشعر؟ تحدث معي...',
    analyze: 'تحليل وتوليد',
    dailyQuote: 'اقتباس اليوم',
    trending: 'الأكثر تداولاً',
    randomQuote: 'اقتباس عشوائي',
    copied: 'تم النسخ بنجاح',
    generating: 'جاري توليد الحكمة...',
    analyzing: 'جاري تحليل حالتك المزاجية...',
    noQuotes: 'لم يتم العثور على اقتباسات',
    favorites: 'المفضلات',
    back: 'رجوع',
    generateMore: 'توليد المزيد',
    detectedEmotion: 'العاطفة المكتشفة',
    personalizedForYou: 'مخصص لك',
    setAsWallpaper: 'تعيين كخلفية',
    homeScreen: 'الشاشة الرئيسية',
    lockScreen: 'شاشة القفل',
    downloading: 'جاري تحضير الخلفية...',
    wallpaperSaved: 'تم حفظ الخلفية في المعرض',
    streak: 'سلسلة الأيام',
    offlineMode: 'وضع عدم الاتصال',
    notifications: 'الإشعارات',
    enableNotifications: 'تفعيل التذكيرات اليومية',
    notificationsEnabledMessage: 'تم تفعيل الإشعارات!',
    notificationsDeniedMessage: 'يرجى تفعيل الإشعارات في الإعدادات',
    newQuoteAvailable: 'اقتباس يومي جديد متاح!',
    includeReligious: 'تضمين الحكمة الدينية',
    religiousWisdom: 'الحكمة المقدسة',
    dailyQuoteNotification: 'اقتباسك المخصص لليوم جاهز...',
    selectLanguage: 'اختر لغتك',
    premiumCustomization: 'تخصيص مميز',
    alignment: 'المحاذاة',
    position: 'الموقع',
    typography: 'الخطوط',
    styleAtmosphere: 'النمط والأجواء',
    styleMinimal: 'بسيط',
    styleNature: 'طبيعة',
    styleCalm: 'هادئ',
    styleWarm: 'دافئ',
    styleDeep: 'عميق',
    styleLuxury: 'فاخر',
    styleCreative: 'إبداعي',
    fontModern: 'عصري',
    fontPremium: 'مميز',
    fontTech: 'تقني',
    fontBold: 'عريض',
    fontElegant: 'أنيق',
    chooseLanguage: 'اختر لغتك',
    selectLanguageSub: 'اختر لغتك المفضلة للمتابعة',
    notificationMood: 'شيء بسيط لمزاجك...',
    notificationFavorites: 'هل أنت مستعد لمزيد من الحكمة مثل مفضلاتك؟',
    copyText: 'نسخ الاقتباس',
  },
  am: {
    appName: 'FeelSync',
    categories: 'ምድቦች',
    exploreWisdom: 'ጥበብን በተለያዩ ጭብጦች ያስሱ',
    moodAnalysis: 'የስሜት ትንተና',
    moodPlaceholder: 'ምን ይሰማዎታል? ያውሩኝ...',
    analyze: 'ተንትን እና አፍልቅ',
    dailyQuote: 'የዕለቱ ጥቅስ',
    trending: 'ተወዳጅ ጥቅሶች',
    randomQuote: 'የዘፈቀደ ጥቅስ',
    copied: 'በተሳካ ሁኔታ ተገልብጧል',
    generating: 'ጥበብን እያፈለቀ ነው...',
    analyzing: 'ስሜትዎን እየተነተነ ነው...',
    noQuotes: 'ምንም ጥቅሶች አልተገኙም',
    favorites: 'ተወዳጆች',
    back: 'ተመለስ',
    generateMore: 'ተጨማሪ አፍልቅ',
    detectedEmotion: 'የተገኘው ስሜት',
    personalizedForYou: 'ለእርስዎ የተዘጋጀ',
    setAsWallpaper: 'እንደ ልጣፍ አዘጋጅ',
    homeScreen: 'መነሻ ስክሪን',
    lockScreen: 'መቆለፊያ ስክሪን',
    downloading: 'ልጣፉን በማዘጋጀት ላይ...',
    wallpaperSaved: 'ልጣፉ በጋለሪ ውስጥ ተቀምጧል',
    streak: 'የቀናት ተከታታይነት',
    offlineMode: 'ከመስመር ውጭ ሁነታ',
    notifications: 'ማሳወቂያዎች',
    enableNotifications: 'የዕለት ተዕለት ማሳሰቢያዎችን ያብሩ',
    notificationsEnabledMessage: 'ማሳወቂያዎች ነቅተዋል!',
    notificationsDeniedMessage: 'እባክዎ በቅንብሮች ውስጥ ማሳወቂያዎችን ያንቁ',
    newQuoteAvailable: 'አዲስ የዕለት ጥቅስ ይገኛል!',
    includeReligious: 'ሃይማኖታዊ ጥቅሶችን አካትት',
    religiousWisdom: 'ቅዱስ ጥበብ',
    dailyQuoteNotification: 'የእርስዎ የዕለት ጥቅስ ተዘጋጅቷል...',
    selectLanguage: 'ቋንቋዎን ይምረጡ',
    premiumCustomization: 'ፕሪሚየም ማበጀት',
    alignment: 'አሰላለፍ',
    position: 'ቦታ',
    typography: 'ታይፖግራፊ',
    styleAtmosphere: 'ቅጥ እና ድባብ',
    styleMinimal: 'ቀላል',
    styleNature: 'ተፈጥሮ',
    styleCalm: 'ረጋ ያለ',
    styleWarm: 'ሞቅ ያለ',
    styleDeep: 'ጥልቅ',
    styleLuxury: 'ቅንጡ',
    styleCreative: 'ፈጠራ',
    fontModern: 'ዘመናዊ',
    fontPremium: 'ፕሪሚየም',
    fontTech: 'ቴክ',
    fontBold: 'ደማቅ',
    fontElegant: 'ውብ',
    chooseLanguage: 'ቋንቋዎን ይምረጡ',
    selectLanguageSub: 'ለመቀጠል የመረጡትን ቋንቋ ይምረጡ',
    notificationMood: 'ለእርስዎ ስሜት የሚሆን ትንሽ ነገር...',
    notificationFavorites: 'እንደ እርስዎ ተወዳጆች ተጨማሪ ጥበብ ለማግኘት ዝግጁ ነዎት?',
    copyText: 'ጥቅሱን ቅዳ',
  },
  om: {
    appName: 'FeelSync',
    categories: 'Ramaddiiwwan',
    exploreWisdom: 'Ogummaa mata dureewwan adda addaa keessatti sakatta’i',
    moodAnalysis: 'Xiinxala Miiraa',
    moodPlaceholder: 'Maaltu sitti dhagahama? Natti himi...',
    analyze: 'Xiinxali & Maddisiisi',
    dailyQuote: 'Caqasa Guyyaa',
    trending: 'Amma kan jaallataman',
    randomQuote: 'Caqasa Tasumaa',
    copied: 'Milkaa’inaan garagalfameera',
    generating: 'Ogummaa maddisiisaa jira...',
    analyzing: 'Miira kee xiinxalaa jira...',
    noQuotes: 'Caqasni hin argamne',
    favorites: 'Jaallataman',
    back: 'Deebi’i',
    generateMore: 'Dabalata Maddisiisi',
    detectedEmotion: 'Miira Argame',
    personalizedForYou: 'Siif kan qophaa’e',
    setAsWallpaper: 'Akka Wallpaperitti tolchi',
    homeScreen: 'Home Screen',
    lockScreen: 'Lock Screen',
    downloading: 'Wallpaper qopheessaa jira...',
    wallpaperSaved: 'Wallpaper galariitti olka’ameera',
    streak: 'Guyyoota Walitti Fufan',
    offlineMode: 'Offline Mode',
    notifications: 'Beeksisa',
    enableNotifications: 'Yaadachiisa Guyyaa Guyyaa Gidduu Galeessa Tolchi',
    notificationsEnabledMessage: 'Beeksisni hojiirra ooleera!',
    notificationsDeniedMessage: 'Maaloo settings keessatti beeksisa tolchi',
    newQuoteAvailable: 'Caqasa guyyaa haaraa argameera!',
    includeReligious: 'Ogummaa Amantii Dabali',
    religiousWisdom: 'Ogummaa Qulqulluu',
    dailyQuoteNotification: 'Caqasni kee kan har’aa qophaa’eera...',
    selectLanguage: 'Afaan kee filadhu',
    premiumCustomization: 'Premium Customization',
    alignment: 'Alignment',
    position: 'Position',
    typography: 'Typography',
    styleAtmosphere: 'Style & Atmosphere',
    styleMinimal: 'Minimal',
    styleNature: 'Nature',
    styleCalm: 'Calm',
    styleWarm: 'Warm',
    styleDeep: 'Deep',
    styleLuxury: 'Luxury',
    styleCreative: 'Creative',
    fontModern: 'Modern',
    fontPremium: 'Premium',
    fontTech: 'Tech',
    fontBold: 'Bold',
    fontElegant: 'Elegant',
    chooseLanguage: 'Afaan kee filadhu',
    selectLanguageSub: 'Itti fufuuf afaan kee filadhu',
    notificationMood: 'Waan xiqqoo miira keetiif ta’u...',
    notificationFavorites: 'Ogummaa dabalataa akka jaallatamtoota keetti qophaa’teettaa?',
    copyText: 'Yaada kana waraabi',
  },
  sw: {
    appName: 'FeelSync',
    categories: 'Kategoria',
    exploreWisdom: 'Gundua hekima kupitia mada tofauti',
    moodAnalysis: 'Uchambuzi wa Mood',
    moodPlaceholder: 'Unajisikiaje? Nizungumzie...',
    analyze: 'Chambua na Tengeneza',
    dailyQuote: 'Nukuu ya Siku',
    trending: 'Zinazovuma Sasa',
    randomQuote: 'Nukuu ya Nasibu',
    copied: 'Imenakiliwa kwa mafanikio',
    generating: 'Inatengeneza hekima...',
    analyzing: 'Inachambua hali yako...',
    noQuotes: 'Hakuna nukuu zilizopatikana',
    favorites: 'Vipendwa',
    back: 'Rudi',
    generateMore: 'Tengeneza Zaidi',
    detectedEmotion: 'Hisia Iliyogunduliwa',
    personalizedForYou: 'Imeandaliwa kwa ajili yako',
    setAsWallpaper: 'Weka kama Karatasi',
    homeScreen: 'Skrini ya Nyumbani',
    lockScreen: 'Skrini ya Kufunga',
    downloading: 'Inatayarisha karatasi...',
    wallpaperSaved: 'Karatasi imehifadhiwa kwenye ghala',
    streak: 'Mfululizo wa Siku',
    offlineMode: 'Hali ya Nje ya Mtandao',
    notifications: 'Arifa',
    enableNotifications: 'Washa Vikumbusho vya Kila Siku',
    notificationsEnabledMessage: 'Arifa zimewashwa!',
    notificationsDeniedMessage: 'Tafadhali washa arifa katika mipangilio',
    newQuoteAvailable: 'Nukuu mpya ya kila siku inapatikana!',
    includeReligious: 'Jumuisha Hekima ya Kidini',
    religiousWisdom: 'Hekima Takatifu',
    dailyQuoteNotification: 'Nukuu yako ya leo iliyobinafsishwa iko tayari...',
    selectLanguage: 'Chagua Lugha Yako',
    premiumCustomization: 'Ubinafsishaji wa Premium',
    alignment: 'Mpangilio',
    position: 'Nafasi',
    typography: 'Uandishi',
    styleAtmosphere: 'Mtindo na Mazingira',
    styleMinimal: 'Kidogo',
    styleNature: 'Asili',
    styleCalm: 'Tulia',
    styleWarm: 'Joto',
    styleDeep: 'Kina',
    styleLuxury: 'Anasa',
    styleCreative: 'Ubunifu',
    fontModern: 'Kisasa',
    fontPremium: 'Premium',
    fontTech: 'Tech',
    fontBold: 'Nene',
    fontElegant: 'Kifahari',
    chooseLanguage: 'Chagua Lugha Yako',
    selectLanguageSub: 'Chagua lugha unayopendelea ili kuendelea',
    notificationMood: 'Kitu kidogo kwa ajili ya hali yako...',
    notificationFavorites: 'Uko tayari kwa hekima zaidi kama vipendwa vyako?',
    copyText: 'Nakili Nukuu',
  },
};

export const CATEGORIES: Category[] = [
  {
    id: 'love',
    name: {
      en: 'Love',
      fr: 'Amour',
      es: 'Amor',
      de: 'Liebe',
      pt: 'Amor',
      hi: 'प्रेम',
      ar: 'الحب',
      am: 'ፍቅር',
      om: 'Jaalala',
      sw: 'Upendo',
    },
    description: {
      en: 'Affection and bonding',
      fr: 'Affection et lien',
      es: 'Afecto y unión',
      de: 'Zuneigung und Bindung',
      pt: 'Afeto e união',
      hi: 'स्नेह और बंधन',
      ar: 'المودة والترابط',
      am: 'ፍቅር እና ትስስር',
      om: 'Jaalala fi hidhata',
      sw: 'Upendo na uhusiano',
    },
    icon: 'Heart',
    abstractMeaning: {
      en: 'The essence of affection and bonding.',
      fr: "L'essence de l'affection et du lien.",
      es: 'La esencia del afecto y la unión.',
      de: 'Die Essenz von Zuneigung und Bindung.',
      pt: 'A essência do afeto e da união.',
      hi: 'स्नेह और बंधन का सार।',
      ar: 'جوهر المودة والترابط.',
      am: 'የፍቅር እና የትስስር ምንነት።',
      om: 'Bu’uura jaalala fi hidhata.',
      sw: 'Kiini cha upendo na uhusiano.',
    },
  },
  {
    id: 'sadness',
    name: {
      en: 'Sad',
      fr: 'Triste',
      es: 'Triste',
      de: 'Traurig',
      pt: 'Triste',
      hi: 'उदास',
      ar: 'حزين',
      am: 'ሀዘን',
      om: 'Gadda',
      sw: 'Huzuni',
    },
    description: {
      en: 'Healing and reflection',
      fr: 'Guérison et réflexion',
      es: 'Sanación y reflexión',
      de: 'Heilung und Reflexion',
      pt: 'Cura e reflexão',
      hi: 'उपचार और प्रतिबिंब',
      ar: 'الشفاء والتأمل',
      am: 'ፈውስ እና ነጸብራቅ',
      om: 'Fayyuu fi xiinxala',
      sw: 'Uponyaji na kutafakari',
    },
    icon: 'CloudRain',
    abstractMeaning: {
      en: 'The path to healing and reflection.',
      fr: 'Le chemin de la guérison et de la réflexion.',
      es: 'El camino hacia la sanación y la reflexión.',
      de: 'Der Weg zur Heilung und Reflexion.',
      pt: 'O caminho para a cura e reflexão.',
      hi: 'उपचार और प्रतिबिंब का मार्ग।',
      ar: 'طريق الشفاء والتأمل.',
      am: 'ወደ ፈውስ እና ነጸብራቅ የሚወስደው መንገድ።',
      om: 'Karaa fayyuu fi xiinxala.',
      sw: 'Njia ya uponyaji na kutafakari.',
    },
  },
  {
    id: 'motivation',
    name: {
      en: 'Motivation',
      fr: 'Motivation',
      es: 'Motivación',
      de: 'Motivation',
      pt: 'Motivação',
      hi: 'प्रेरणा',
      ar: 'تحفيز',
      am: 'ተነሳሽነት',
      om: 'Kaka’umsa',
      sw: 'Motisha',
    },
    description: {
      en: 'Energy and drive',
      fr: 'Énergie et entraînement',
      es: 'Energía e impulso',
      de: 'Energie und Antrieb',
      pt: 'Energia e impulso',
      hi: 'ऊर्जा और ड्राइव',
      ar: 'الطاقة والدافع',
      am: 'ጉልበት እና ተነሳሽነት',
      om: 'Annisaa fi kaka’umsa',
      sw: 'Nishati na nguvu',
    },
    icon: 'Zap',
    abstractMeaning: {
      en: 'The spark that ignites action and persistence.',
      fr: "L'étincelle qui déclenche l'action et la persévérance.",
      es: 'La chispa que enciende la acción y la persistencia.',
      de: 'Der Funke, der Handeln und Ausdauer entfacht.',
      pt: 'A faísca que inflama a ação e a persistência.',
      hi: 'वह चिंगारी जो क्रिया और दृढ़ता को प्रज्वलित करती है।',
      ar: 'الشرارة التي تشعل العمل والمثابرة.',
      am: 'ድርጊትን እና ጽናትን የሚያቀጣጥል ብልጭታ።',
      om: 'Billaqa gochaa fi obsa kakaasu.',
      sw: 'Cheche inayowasha hatua na uvumilivu.',
    },
  },
  {
    id: 'success',
    name: {
      en: 'Success',
      fr: 'Succès',
      es: 'Éxito',
      de: 'Erfolg',
      pt: 'Sucesso',
      hi: 'सफलता',
      ar: 'نجاح',
      am: 'ስኬት',
      om: 'Milkaa’ina',
      sw: 'Mafanikio',
    },
    description: {
      en: 'Growth, achievement, ambition',
      fr: 'Croissance, réussite, ambition',
      es: 'Crecimiento, logro, ambición',
      de: 'Wachstum, Leistung, Ehrgeiz',
      pt: 'Crescimento, conquista, ambição',
      hi: 'विकास, उपलब्धि, महत्वाकांक्षा',
      ar: 'النمو والإنجاز والطموح',
      am: 'እድገት፣ ስኬት፣ ምኞት',
      om: 'Guddina, milkaa’ina, hawwii',
      sw: 'Ukuaji, mafanikio, tamaa',
    },
    icon: 'Trophy',
    abstractMeaning: {
      en: 'The realization of goals and personal growth.',
      fr: 'La réalisation des objectifs et la croissance personnelle.',
      es: 'La realización de metas y el crecimiento personal.',
      de: 'Die Verwirklichung von Zielen und persönliches Wachstum.',
      pt: 'A realização de objetivos e crescimento pessoal.',
      hi: 'लक्ष्यों की प्राप्ति और व्यक्तिगत विकास।',
      ar: 'تحقيق الأهداف والنمو الشخصي.',
      am: 'የግብ እና የግል እድገት እውን መሆን።',
      om: 'Galma gahuu fi guddina dhuunfaa.',
      sw: 'Utimilifu wa malengo na ukuaji wa kibinafsi.',
    },
  },
  {
    id: 'life',
    name: {
      en: 'Life',
      fr: 'Vie',
      es: 'Vida',
      de: 'Leben',
      pt: 'Vida',
      hi: 'जीवन',
      ar: 'حياة',
      am: 'ህይወት',
      om: 'Jireenya',
      sw: 'Maisha',
    },
    description: {
      en: 'Journey, experience, existence',
      fr: 'Voyage, expérience, existence',
      es: 'Viaje, experiencia, existencia',
      de: 'Reise, Erfahrung, Existenz',
      pt: 'Jornada, experiência, existência',
      hi: 'यात्रा, अनुभव, अस्तित्व',
      ar: 'الرحلة والخبرة والوجود',
      am: 'ጉዞ፣ ልምድ፣ ህልውና',
      om: 'Adeemsa, muuxannoo, jireenya',
      sw: 'Safari, uzoefu, uwepo',
    },
    icon: 'Compass',
    abstractMeaning: {
      en: 'The continuous journey of learning and being.',
      fr: "Le voyage continu d'apprentissage et d'être.",
      es: 'El viaje continuo de aprender y ser.',
      de: 'Die kontinuierliche Reise des Lernens und Seins.',
      pt: 'A jornada contínua de aprendizado e ser.',
      hi: 'सीखने और होने की निरंतर यात्रा।',
      ar: 'رحلة مستمرة من التعلم والوجود.',
      am: 'ቀጣይነት ያለው የመማር እና የመሆን ጉዞ።',
      om: 'Adeemsa barachuu fi jiraachuu itti fufiinsa qabu.',
      sw: 'Safari inayoendelea ya kujifunza na kuwepo.',
    },
  },
  {
    id: 'friendship',
    name: {
      en: 'Friendship',
      fr: 'Amitié',
      es: 'Amistad',
      de: 'Freundschaft',
      pt: 'Amizade',
      hi: 'मित्रता',
      ar: 'صداقة',
      am: 'ጓደኝነት',
      om: 'Michummaa',
      sw: 'Urafiki',
    },
    description: {
      en: 'Loyalty, support, companionship',
      fr: 'Loyauté, soutien, camaraderie',
      es: 'Lealtad, apoyo, compañerismo',
      de: 'Loyalität, Unterstützung, Kameradschaft',
      pt: 'Lealdade, apoio, companheirismo',
      hi: 'वफादारी, समर्थन, साथ',
      ar: 'الولاء والدعم والرفقة',
      am: 'ታማኝነት፣ ድጋፍ፣ ጓደኝነት',
      om: 'Amanamummaa, deeggarsa, hiriyyummaa',
      sw: 'Uaminifu, msaada, urafiki',
    },
    icon: 'Users',
    abstractMeaning: {
      en: 'The bond of mutual trust and support.',
      fr: 'Le lien de confiance et de soutien mutuel.',
      es: 'El vínculo de confianza y apoyo mutuo.',
      de: 'Die Bindung des gegenseitigen Vertrauens und der Unterstützung.',
      pt: 'O vínculo de confiança e apoio mútuo.',
      hi: 'पारस्परिक विश्वास और समर्थन का बंधन।',
      ar: 'رابطة الثقة المتبادلة والدعم.',
      am: 'የጋራ መተማመን እና የድጋፍ ትስስር።',
      om: 'Waliin amanamummaa fi deeggarsa.',
      sw: 'Uhusiano wa kuaminiana na kusaidiana.',
    },
  },
  {
    id: 'bible',
    name: {
      en: 'Bible Quotes',
      fr: 'Citations Bibliques',
      es: 'Citas Bíblicas',
      de: 'Bibelzitate',
      pt: 'Citações Bíblicas',
      hi: 'बाइबल के विचार',
      ar: 'اقتباسات من الكتاب المقدس',
      am: 'የመጽሐፍ ቅዱስ ጥቅሶች',
      om: 'Caqasoota Kitaaba Qulqulluu',
      sw: 'Nukuu za Biblia',
    },
    description: {
      en: 'Faith, wisdom, scripture',
      fr: 'Foi, sagesse, écriture',
      es: 'Fe, sabiduría, escritura',
      de: 'Glaube, Weisheit, Schrift',
      pt: 'Fé, sabedoria, escritura',
      hi: 'विश्वास, ज्ञान, शास्त्र',
      ar: 'الإيمان والحكمة والكتاب المقدس',
      am: 'እምነት፣ ጥበብ፣ ቅዱሳት መጻሕፍት',
      om: 'Amantii, ogummaa, barreeffama qulqulluu',
      sw: 'Imani, hekima, maandiko',
    },
    icon: 'BookOpen',
    abstractMeaning: {
      en: 'Spiritual guidance through sacred texts.',
      fr: 'Guidance spirituelle à travers les textes sacrés.',
      es: 'Guía espiritual a través de textos sagrados.',
      de: 'Spirituelle Führung durch heilige Texte.',
      pt: 'Orientação espiritual através de textos sagrados.',
      hi: 'पवित्र ग्रंथों के माध्यम से आध्यात्मिक मार्गदर्शन।',
      ar: 'الإرشاد الروحي من خلال النصوص المقدسة.',
      am: 'በቅዱሳት መጻሕፍት በኩል መንፈሳዊ መመሪያ።',
      om: 'Qajeelfama hafuuraa barreeffama qulqulluutiin.',
      sw: 'Mwongozo wa kiroho kupitia maandiko matakatifu.',
    },
  },
  {
    id: 'quran',
    name: {
      en: 'Quran Quotes',
      fr: 'Citations du Coran',
      es: 'Citas del Corán',
      de: 'Koran-Zitate',
      pt: 'Citações do Alcorão',
      hi: 'कुरान के विचार',
      ar: 'اقتباسات من القرآن',
      am: 'የቁርኣን ጥቅሶች',
      om: 'Caqasoota Qur’aanaa',
      sw: 'Nukuu za Quran',
    },
    description: {
      en: 'Peace, guidance, revelation',
      fr: 'Paix, guidance, révélation',
      es: 'Paz, guía, revelación',
      de: 'Frieden, Führung, Offenbarung',
      pt: 'Paz, orientação, revelação',
      hi: 'शांति, मार्गदर्शन, रहस्योद्घाटन',
      ar: 'السلام والهدى والوحي',
      am: 'ሰላም፣ መመሪያ፣ መገለጥ',
      om: 'Nagaa, qajeelfama, mul’ata',
      sw: 'Amani, mwongozo, ufunuo',
    },
    icon: 'Moon',
    abstractMeaning: {
      en: 'Divine wisdom and inner peace.',
      fr: 'Sagesse divine et paix intérieure.',
      es: 'Sabiduría divina y paz interior.',
      de: 'Göttliche Weisheit und innerer Frieden.',
      pt: 'Sabedoria divina e paz interior.',
      hi: 'दिव्य ज्ञान और आंतरिक शांति।',
      ar: 'الحكمة الإلهية والسلام الداخلي.',
      am: 'መለኮታዊ ጥበብ እና ውስጣዊ ሰላም።',
      om: 'Ogummaa Waaqaa fi nagaa keessaa.',
      sw: 'Hekima ya kimungu na amani ya ndani.',
    },
  },
];
