import { Category, Language, UITranslationKeys } from "./types";

export const UI_TRANSLATIONS: Record<
  Language,
  Partial<Record<UITranslationKeys, string>>
> = {
  en: {
    appName: "FeelSync",
    categories: "Categories",
    exploreWisdom: "Explore wisdom across different themes",
    soulInsight: "Soul Insight",
    moodPlaceholder: "How does your soul feel? Speak to me...",
    analyze: "Seek Wisdom",
    dailyQuote: "Daily Wisdom",
    trending: "Trending Wisdom",
    randomQuote: "Random Wisdom",
    copied: "Wisdom copied successfully",
    generating: "Seeking wisdom...",
    analyzing: "Listening to your soul...",
    noQuotes: "No wisdom found",
    favorites: "Treasured Wisdom",
    back: "Return",
    generateMore: "Seek More",
    detectedEmotion: "Soul State",
    personalizedForYou: "Personalized for your soul",
    setAsWallpaper: "Set as Soul Wallpaper",
    homeScreen: "Home Screen",
    lockScreen: "Lock Screen",
    downloading: "Preparing wisdom...",
    wallpaperSaved: "Wisdom saved to gallery",
    streak: "Wisdom Streak",
    offlineMode: "Soul Offline Mode",
    notifications: "Soul Reminders",
    enableNotifications: "Enable Daily Reminders",
    notificationsEnabledMessage: "Reminders enabled!",
    notificationsDeniedMessage: "Please enable notifications in settings",
    newQuoteAvailable: "New daily wisdom available!",
    religiousWisdom: "Sacred Wisdom",
    dailyQuoteNotification: "Your personalized wisdom for today is ready...",
    selectLanguage: "Choose Your Language",
    premiumCustomization: "Premium Soul Customization",
    alignment: "Alignment",
    position: "Position",
    typography: "Typography",
    styleAtmosphere: "Soul Atmosphere",
    styleMinimal: "Minimal",
    styleNature: "Nature",
    styleCalm: "Calm",
    styleWarm: "Warm",
    styleDeep: "Deep",
    styleLuxury: "Luxury",
    styleCreative: "Creative",
    aiBackground: "AI Background",
    styleAbstract: "Abstract",
    styleSerene: "Serene",
    styleVibrant: "Vibrant",
    generateBackground: "Generate Background",
    fontModern: "Modern",
    fontPremium: "Premium",
    fontTech: "Tech",
    fontBold: "Bold",
    fontElegant: "Elegant",
    chooseLanguage: "Choose Your Language",
    selectLanguageSub: "Select your preferred language to continue",
    notificationMood: "Something for your soul...",
    notificationFavorites: "Ready for more wisdom like your favorites?",
    copyText: "Copy Wisdom",
    onboardingTitle1: "Welcome to FeelSync",
    onboardingSub1: "Your daily companion for soul balance and wisdom.",
    onboardingTitle2: "Soul Insight",
    onboardingSub2:
      "Talk to your inner wisdom to get personalized quotes based on how you feel.",
    onboardingTitle3: "Daily Inspiration",
    onboardingSub3:
      "Receive a hand-picked wisdom every morning to start your day right.",
    getStarted: "Begin Journey",
    next: "Next",
    skip: "Skip",
    goPremium: "Unlock Soul Pro",
    premiumTitle: "Unlock Full Potential",
    premiumSub: "Support the app and get exclusive features",
    premiumFeature1: "Exclusive Soul Styles",
    premiumFeature2: "Ad-Free Experience",
    premiumFeature3: "Premium Soul Typography",
    premiumFeature4: "Unlimited Soul Insights",
    upgradeNow: "Upgrade Now",
    restorePurchases: "Restore Purchases",
    settings: "Settings",
    rateApp: "Rate FeelSync",
    feedback: "Send Feedback",
    privacyPolicy: "Privacy Policy",
    termsOfService: "Terms of Service",
    about: "About FeelSync",
    version: "Version 1.0.0",
    shareApp: "Share FeelSync",
  },
  fr: {
    appName: "FeelSync",
    categories: "Catégories",
    exploreWisdom: "Explorez la sagesse à travers différents thèmes",
    soulInsight: "Sagesse de l'âme",
    moodPlaceholder: "Comment se sent votre âme ? Parlez-moi...",
    analyze: "Chercher la sagesse",
    dailyQuote: "Sagesse quotidienne",
    trending: "Sagesse tendance",
    randomQuote: "Sagesse aléatoire",
    copied: "Sagesse copiée avec succès",
    generating: "Recherche de sagesse...",
    analyzing: "À l'écoute de votre âme...",
    noQuotes: "Aucune sagesse trouvée",
    favorites: "Sagesse précieuse",
    back: "Retour",
    generateMore: "Chercher plus",
    detectedEmotion: "État de l'âme",
    personalizedForYou: "Personnalisé pour votre âme",
    setAsWallpaper: "Définir comme fond d'écran de l'âme",
    homeScreen: "Écran d'accueil",
    lockScreen: "Écran de verrouillage",
    downloading: "Préparation de la sagesse...",
    wallpaperSaved: "Sagesse enregistrée dans la galerie",
    streak: "Série de sagesse",
    offlineMode: "Mode hors ligne de l'âme",
    notifications: "Rappels de l'âme",
    enableNotifications: "Activer les rappels quotidiens",
    notificationsEnabledMessage: "Rappels activés !",
    notificationsDeniedMessage:
      "Veuillez activer les notifications dans les paramètres",
    newQuoteAvailable: "Nouvelle sagesse quotidienne disponible !",
    religiousWisdom: "Sagesse sacrée",
    dailyQuoteNotification:
      "Votre sagesse personnalisée pour aujourd'hui est prête...",
    selectLanguage: "Choisissez votre langue",
    premiumCustomization: "Personnalisation premium de l'âme",
    alignment: "Alignement",
    position: "Position",
    typography: "Typographie",
    styleAtmosphere: "Atmosphère de l'âme",
    styleMinimal: "Minimaliste",
    styleNature: "Nature",
    styleCalm: "Calme",
    styleWarm: "Chaleureux",
    styleDeep: "Profond",
    styleLuxury: "Luxe",
    styleCreative: "Créatif",
    fontModern: "Moderne",
    fontPremium: "Premium",
    fontTech: "Technique",
    fontBold: "Gras",
    fontElegant: "Élégant",
    chooseLanguage: "Choisissez votre langue",
    selectLanguageSub: "Sélectionnez votre langue préférée pour continuer",
    notificationMood: "Quelque chose pour votre âme...",
    notificationFavorites: "Prêt pour plus de sagesse comme vos favoris ?",
    copyText: "Copier la sagesse",
    onboardingTitle1: "Bienvenue sur FeelSync",
    onboardingSub1:
      "Votre compagnon quotidien pour l'équilibre de l'âme et la sagesse.",
    onboardingTitle2: "Sagesse de l'âme",
    onboardingSub2:
      "Parlez à votre sagesse intérieure pour obtenir des citations personnalisées basées sur ce que vous ressentez.",
    onboardingTitle3: "Inspiration quotidienne",
    onboardingSub3:
      "Recevez une sagesse triée sur le volet chaque matin pour bien commencer votre journée.",
    getStarted: "Commencer le voyage",
    next: "Suivant",
    skip: "Passer",
    goPremium: "Débloquer Soul Pro",
    premiumTitle: "Débloquer le plein potentiel",
    premiumSub:
      "Soutenez l'application et obtenez des fonctionnalités exclusives",
    premiumFeature1: "Styles d'âme exclusifs",
    premiumFeature2: "Expérience sans publicité",
    premiumFeature3: "Typographie d'âme premium",
    premiumFeature4: "Aperçus d'âme illimités",
    upgradeNow: "Mettre à jour maintenant",
    restorePurchases: "Restaurer les achats",
    settings: "Paramètres",
    rateApp: "Évaluer FeelSync",
    feedback: "Envoyer des commentaires",
    privacyPolicy: "Politique de confidentialité",
    termsOfService: "Conditions d'utilisation",
    about: "À propos de FeelSync",
    version: "Version 1.0.0",
    shareApp: "Partager FeelSync",
  },
  es: {
    appName: "FeelSync",
    categories: "Categorías",
    exploreWisdom: "Explora la sabiduría en diferentes temas",
    soulInsight: "Sabiduría del Alma",
    moodPlaceholder: "¿Cómo se siente tu alma? Cuéntame...",
    analyze: "Buscar Sabiduría",
    dailyQuote: "Sabiduría Diaria",
    trending: "Sabiduría en Tendencia",
    randomQuote: "Sabiduría Aleatoria",
    copied: "Sabiduría copiada con éxito",
    generating: "Buscando sabiduría...",
    analyzing: "Escuchando a tu alma...",
    noQuotes: "No se encontró sabiduría",
    favorites: "Sabiduría Tesoro",
    back: "Volver",
    generateMore: "Buscar más",
    detectedEmotion: "Estado del Alma",
    personalizedForYou: "Personalizado para tu alma",
    setAsWallpaper: "Definir como Fondo del Alma",
    homeScreen: "Pantalla de Inicio",
    lockScreen: "Pantalla de Bloqueo",
    downloading: "Preparando sabiduría...",
    wallpaperSaved: "Sabiduría guardada en la galería",
    streak: "Racha de Sabiduría",
    offlineMode: "Modo Offline del Alma",
    notifications: "Recordatorios del Alma",
    enableNotifications: "Activar Recordatorios Diarios",
    notificationsEnabledMessage: "¡Recordatorios activados!",
    notificationsDeniedMessage:
      "Por favor activa las notificaciones en ajustes",
    newQuoteAvailable: "¡Nueva sabiduría diaria disponible!",
    religiousWisdom: "Sabiduría Sagrada",
    dailyQuoteNotification: "Tu sabiduría personalizada para hoy está lista...",
    selectLanguage: "Elige tu idioma",
    premiumCustomization: "Personalización Premium del Alma",
    alignment: "Alineación",
    position: "Posición",
    typography: "Tipografía",
    styleAtmosphere: "Atmósfera del Alma",
    styleMinimal: "Minimalista",
    styleNature: "Naturaleza",
    styleCalm: "Calma",
    styleWarm: "Cálido",
    styleDeep: "Profundo",
    styleLuxury: "Lujo",
    styleCreative: "Creativo",
    fontModern: "Moderno",
    fontPremium: "Premium",
    fontTech: "Tecnológico",
    fontBold: "Negrita",
    fontElegant: "Elegante",
    chooseLanguage: "Elige tu idioma",
    selectLanguageSub: "Selecciona tu idioma preferido para continuar",
    notificationMood: "Algo para tu alma...",
    notificationFavorites: "¿Listo para más sabiduría como tus favoritos?",
    copyText: "Copiar Sabiduría",
    onboardingTitle1: "Bienvenido a FeelSync",
    onboardingSub1:
      "Tu compañero diario para el equilibrio del alma y la sabiduría.",
    onboardingTitle2: "Sabiduría del Alma",
    onboardingSub2:
      "Habla con tu sabiduría interior para obtener citas personalizadas basadas en cómo te sientes.",
    onboardingTitle3: "Inspiración Diaria",
    onboardingSub3:
      "Recibe una sabiduría seleccionada cada mañana para comenzar bien tu día.",
    getStarted: "Comenzar Viaje",
    next: "Siguiente",
    skip: "Omitir",
    goPremium: "Desbloquear Soul Pro",
    premiumTitle: "Desbloquear Todo el Potencial",
    premiumSub: "Apoya la aplicación y obtén funciones exclusivas",
    premiumFeature1: "Estilos de Alma Exclusivos",
    premiumFeature2: "Experiencia sin Anuncios",
    premiumFeature3: "Tipografía de Alma Premium",
    premiumFeature4: "Sabiduría del Alma Ilimitada",
    upgradeNow: "Actualizar Ahora",
    restorePurchases: "Restaurar Compras",
    settings: "Ajustes",
    rateApp: "Calificar FeelSync",
    feedback: "Enviar Comentarios",
    privacyPolicy: "Política de Privacidad",
    termsOfService: "Términos de Servicio",
    about: "Acerca de FeelSync",
    version: "Version 1.0.0",
    shareApp: "Compartir FeelSync",
  },
  de: {
    appName: "FeelSync",
    categories: "Kategorien",
    exploreWisdom: "Entdecke Weisheit in verschiedenen Themen",
    soulInsight: "Seeleneinblick",
    moodPlaceholder: "Wie fühlt sich deine Seele an? Sprich zu mir...",
    analyze: "Weisheit suchen",
    dailyQuote: "Tägliche Weisheit",
    trending: "Angesagte Weisheit",
    randomQuote: "Zufällige Weisheit",
    copied: "Weisheit erfolgreich kopiert",
    generating: "Suche Weisheit...",
    analyzing: "Höre auf deine Seele...",
    noQuotes: "Keine Weisheit gefunden",
    favorites: "Geschätzte Weisheit",
    back: "Zurück",
    generateMore: "Mehr suchen",
    detectedEmotion: "Seelenzustand",
    personalizedForYou: "Personalisiert für deine Seele",
    setAsWallpaper: "Als Seelen-Hintergrund festlegen",
    homeScreen: "Startbildschirm",
    lockScreen: "Sperrbildschirm",
    downloading: "Bereite Weisheit vor...",
    wallpaperSaved: "Weisheit in Galerie gespeichert",
    streak: "Weisheits-Serie",
    offlineMode: "Seelen-Offline-Modus",
    notifications: "Seelen-Erinnerungen",
    enableNotifications: "Tägliche Erinnerungen aktivieren",
    notificationsEnabledMessage: "Erinnerungen aktiviert!",
    notificationsDeniedMessage:
      "Bitte aktiviere Benachrichtigungen in den Einstellungen",
    newQuoteAvailable: "Neue tägliche Weisheit verfügbar!",
    religiousWisdom: "Heilige Weisheit",
    dailyQuoteNotification:
      "Deine personalisierte Weisheit für heute ist bereit...",
    selectLanguage: "Wähle deine Sprache",
    premiumCustomization: "Premium Seelen-Anpassung",
    alignment: "Ausrichtung",
    position: "Position",
    typography: "Typografie",
    styleAtmosphere: "Seelen-Atmosphäre",
    styleMinimal: "Minimalistisch",
    styleNature: "Natur",
    styleCalm: "Ruhig",
    styleWarm: "Warm",
    styleDeep: "Tief",
    styleLuxury: "Luxus",
    styleCreative: "Kreativ",
    fontModern: "Modern",
    fontPremium: "Premium",
    fontTech: "Tech",
    fontBold: "Fett",
    fontElegant: "Elegant",
    chooseLanguage: "Wähle deine Sprache",
    selectLanguageSub: "Wähle deine bevorzugte Sprache, um fortzufahren",
    notificationMood: "Etwas für deine Seele...",
    notificationFavorites: "Bereit für mehr Weisheit wie deine Favoriten?",
    copyText: "Weisheit kopieren",
    onboardingTitle1: "Willkommen bei FeelSync",
    onboardingSub1: "Dein täglicher Begleiter für Seelenbalance und Weisheit.",
    onboardingTitle2: "Seeleneinblick",
    onboardingSub2:
      "Sprich mit deiner inneren Weisheit, um personalisierte Zitate basierend auf deinem Befinden zu erhalten.",
    onboardingTitle3: "Tägliche Inspiration",
    onboardingSub3:
      "Erhalte jeden Morgen eine handverlesene Weisheit, um deinen Tag richtig zu beginnen.",
    getStarted: "Reise beginnen",
    next: "Weiter",
    skip: "Überspringen",
    goPremium: "Soul Pro freischalten",
    premiumTitle: "Volles Potenzial freischalten",
    premiumSub: "Unterstütze die App und erhalte exklusive Funktionen",
    premiumFeature1: "Exklusive Seelen-Stile",
    premiumFeature2: "Werbefreies Erlebnis",
    premiumFeature3: "Premium Seelen-Typografie",
    premiumFeature4: "Unbegrenzte Seeleneinblicke",
    upgradeNow: "Jetzt upgraden",
    restorePurchases: "Käufe wiederherstellen",
    settings: "Einstellungen",
    rateApp: "FeelSync bewerten",
    feedback: "Feedback senden",
    privacyPolicy: "Datenschutzrichtlinie",
    termsOfService: "Nutzungsbedingungen",
    about: "Über FeelSync",
    version: "Version 1.0.0",
    shareApp: "FeelSync teilen",
  },
  pt: {
    appName: "FeelSync",
    categories: "Categorias",
    exploreWisdom: "Explore a sabedoria em diferentes temas",
    soulInsight: "Sabedoria da Alma",
    moodPlaceholder: "Como se sente a sua alma? Fale comigo...",
    analyze: "Buscar Sabedoria",
    dailyQuote: "Sabedoria Diária",
    trending: "Sabedoria em Tendência",
    randomQuote: "Sabedoria Aleatória",
    copied: "Sabedoria copiada com sucesso",
    generating: "Buscando sabedoria...",
    analyzing: "Ouvindo a sua alma...",
    noQuotes: "Nenhuma sabedoria encontrada",
    favorites: "Sabedoria Tesouro",
    back: "Voltar",
    generateMore: "Buscar mais",
    detectedEmotion: "Estado da Alma",
    personalizedForYou: "Personalizado para a sua alma",
    setAsWallpaper: "Definir como Papel de Parede da Alma",
    homeScreen: "Ecrã Principal",
    lockScreen: "Ecrã de Bloqueio",
    downloading: "Preparando sabedoria...",
    wallpaperSaved: "Sabidoria guardada na galeria",
    streak: "Sequência de Sabedoria",
    offlineMode: "Modo Offline da Alma",
    notifications: "Lembretes da Alma",
    enableNotifications: "Ativar Lembretes Diários",
    notificationsEnabledMessage: "Lembretes ativados!",
    notificationsDeniedMessage:
      "Por favor ative as notificações nas definições",
    newQuoteAvailable: "Nova sabedoria diária disponível!",
    religiousWisdom: "Sabedoria Sagrada",
    dailyQuoteNotification:
      "A sua sabedoria personalizada para hoje está pronta...",
    selectLanguage: "Escolha o seu idioma",
    premiumCustomization: "Personalização Premium da Alma",
    alignment: "Alinhamento",
    position: "Posição",
    typography: "Tipografia",
    styleAtmosphere: "Atmosfera da Alma",
    styleMinimal: "Minimalista",
    styleNature: "Natureza",
    styleCalm: "Calma",
    styleWarm: "Quente",
    styleDeep: "Profundo",
    styleLuxury: "Luxo",
    styleCreative: "Criativo",
    fontModern: "Moderno",
    fontPremium: "Premium",
    fontTech: "Tecnológico",
    fontBold: "Negrito",
    fontElegant: "Elegante",
    chooseLanguage: "Escolha o seu idioma",
    selectLanguageSub: "Selecione o seu idioma preferido para continuar",
    notificationMood: "Algo para a sua alma...",
    notificationFavorites: "Pronto para mais sabedoria como os seus favoritos?",
    copyText: "Copiar Sabedoria",
    onboardingTitle1: "Bem-vindo ao FeelSync",
    onboardingSub1:
      "O seu companheiro diário para o equilíbrio da alma e sabedoria.",
    onboardingTitle2: "Sabidoria da Alma",
    onboardingSub2:
      "Fale com a sua sabedoria interior para obter citações personalizadas com base em como se sente.",
    onboardingTitle3: "Inspiração Diária",
    onboardingSub3:
      "Receba uma sabedoria selecionada todas as manhãs para começar bem o seu dia.",
    getStarted: "Iniciar Viagem",
    next: "Seguinte",
    skip: "Saltar",
    goPremium: "Desbloquear Soul Pro",
    premiumTitle: "Desbloquear Todo o Potencial",
    premiumSub: "Apoie a aplicação e obtenha funcionalidades exclusivas",
    premiumFeature1: "Estilos de Alma Exclusivos",
    premiumFeature2: "Experiencia sem Anúncios",
    premiumFeature3: "Tipografia de Alma Premium",
    premiumFeature4: "Sabedoria da Alma Ilimitada",
    upgradeNow: "Atualizar Agora",
    restorePurchases: "Restaurar Compras",
    settings: "Definições",
    rateApp: "Avaliar FeelSync",
    feedback: "Enviar Feedback",
    privacyPolicy: "Política de Privacidade",
    termsOfService: "Termos de Serviço",
    about: "Sobre o FeelSync",
    version: "Version 1.0.0",
    shareApp: "Partilhar FeelSync",
  },
  hi: {
    appName: "FeelSync",
    categories: "श्रेणियाँ",
    exploreWisdom: "विभिन्न विषयों में ज्ञान खोजें",
    soulInsight: "आत्मा की अंतर्दृष्टि",
    moodPlaceholder: "आपकी आत्मा कैसा महसूस कर रही है? मुझसे बात करें...",
    analyze: "ज्ञान खोजें",
    dailyQuote: "दैनिक ज्ञान",
    trending: "ट्रेंडिंग ज्ञान",
    randomQuote: "यादृच्छिक ज्ञान",
    copied: "ज्ञान सफलतापूर्वक कॉपी किया गया",
    generating: "ज्ञान खोजा जा रहा है...",
    analyzing: "आपकी आत्मा की बात सुनी जा रही है...",
    noQuotes: "कोई ज्ञान नहीं मिला",
    favorites: "पसंदीदा ज्ञान",
    back: "पीछे",
    generateMore: "और खोजें",
    detectedEmotion: "आत्मा की स्थिति",
    personalizedForYou: "आपकी आत्मा के लिए व्यक्तिगत",
    setAsWallpaper: "आत्मा वॉलपेपर के रूप में सेट करें",
    homeScreen: "होम स्क्रीन",
    lockScreen: "लॉक स्क्रीन",
    downloading: "ज्ञान तैयार किया जा रहा है...",
    wallpaperSaved: "ज्ञान गैलरी में सहेजा गया",
    streak: "ज्ञान का सिलसिला",
    offlineMode: "आत्मा ऑफ़लाइन मोड",
    notifications: "आत्मा अनुस्मारक",
    enableNotifications: "दैनिक अनुस्मारक सक्षम करें",
    notificationsEnabledMessage: "अनुस्मारक सक्षम किए गए!",
    notificationsDeniedMessage: "कृपया सेटिंग्स में सूचनाएं सक्षम करें",
    newQuoteAvailable: "नया दैनिक ज्ञान उपलब्ध है!",
    religiousWisdom: "पवित्र ज्ञान",
    dailyQuoteNotification: "आज के लिए आपका व्यक्तिगत ज्ञान तैयार है...",
    selectLanguage: "अपनी भाषा चुनें",
    premiumCustomization: "प्रीमियम आत्मा अनुकूलन",
    alignment: "संरेखण",
    position: "स्थिति",
    typography: "टाइपोग्राफी",
    styleAtmosphere: "आत्मा का वातावरण",
    styleMinimal: "न्यूनतम",
    styleNature: "प्रकृति",
    styleCalm: "शांत",
    styleWarm: "गर्म",
    styleDeep: "गहरा",
    styleLuxury: "लक्जरी",
    styleCreative: "रचनात्मक",
    fontModern: "आधुनिक",
    fontPremium: "प्रीमियम",
    fontTech: "टेक",
    fontBold: "बोल्ड",
    fontElegant: "सुरुचिपूर्ण",
    chooseLanguage: "अपनी भाषा चुनें",
    selectLanguageSub: "जारी रखने के लिए अपनी पसंदीदा भाषा चुनें",
    notificationMood: "आपकी आत्मा के लिए कुछ खास...",
    notificationFavorites:
      "क्या आप अपने पसंदीदा जैसे और ज्ञान के लिए तैयार हैं?",
    copyText: "ज्ञान कॉपी करें",
    onboardingTitle1: "FeelSync में आपका स्वागत है",
    onboardingSub1: "आत्मा के संतुलन और ज्ञान के लिए आपका दैनिक साथी।",
    onboardingTitle2: "आत्मा की अंतर्दृष्टि",
    onboardingSub2:
      "आप कैसा महसूस करते हैं, इसके आधार पर व्यक्तिगत उद्धरण प्राप्त करने के लिए अपनी आंतरिक बुद्धिमत्ता से बात करें।",
    onboardingTitle3: "दैनिक प्रेरणा",
    onboardingSub3:
      "अपने दिन की सही शुरुआत करने के लिए हर सुबह एक चुनिंदा ज्ञान प्राप्त करें।",
    getStarted: "यात्रा शुरू करें",
    next: "अगला",
    skip: "छोड़ें",
    goPremium: "Soul Pro अनलॉक करें",
    premiumTitle: "पूर्ण क्षमता अनलॉक करें",
    premiumSub: "ऐप का समर्थन करें और विशेष सुविधाएं प्राप्त करें",
    premiumFeature1: "विशेष आत्मा शैलियाँ",
    premiumFeature2: "विज्ञापन-मुक्त अनुभव",
    premiumFeature3: "प्रीमियम आत्मा टाइपोग्राफी",
    premiumFeature4: "असीमित आत्मा अंतर्दृष्टि",
    upgradeNow: "अभी अपग्रेड करें",
    restorePurchases: "खरीदें पुनर्स्थापित करें",
    settings: "सेटिंग्स",
    rateApp: "FeelSync को रेट करें",
    feedback: "प्रतिक्रिया भेजें",
    privacyPolicy: "गोपनीयता नीति",
    termsOfService: "सेवा की शर्तें",
    about: "FeelSync के बारे में",
    version: "Version 1.0.0",
    shareApp: "FeelSync साझा करें",
  },
  ar: {
    appName: "FeelSync",
    categories: "الفئات",
    exploreWisdom: "استكشف الحكمة عبر مواضيع مختلفة",
    soulInsight: "بصيرة الروح",
    moodPlaceholder: "كيف تشعر روحك؟ تحدث إلي...",
    analyze: "اطلب الحكمة",
    dailyQuote: "حكمة اليوم",
    trending: "حكمة رائجة",
    randomQuote: "حكمة عشوائية",
    copied: "تم نسخ الحكمة بنجاح",
    generating: "جاري طلب الحكمة...",
    analyzing: "جاري الاستماع لروحك...",
    noQuotes: "لم يتم العثور على حكمة",
    favorites: "حكمة ثمينة",
    back: "رجوع",
    generateMore: "اطلب المزيد",
    detectedEmotion: "حالة الروح",
    personalizedForYou: "مخصص لروحك",
    setAsWallpaper: "تعيين كخلفية للروح",
    homeScreen: "الشاشة الرئيسية",
    lockScreen: "شاشة القفل",
    downloading: "جاري تحضير الحكمة...",
    wallpaperSaved: "تم حفظ الحكمة في المعرض",
    streak: "سلسلة الحكمة",
    offlineMode: "وضع الروح أوفلاين",
    notifications: "تذكيرات الروح",
    enableNotifications: "تفعيل التذكيرات اليومية",
    notificationsEnabledMessage: "تم تفعيل التذكيرات!",
    notificationsDeniedMessage: "يرجى تفعيل الإشعارات في الإعدادات",
    newQuoteAvailable: "حكمة يومية جديدة متاحة!",
    religiousWisdom: "حكمة مقدسة",
    dailyQuoteNotification: "حكمتك المخصصة لليوم جاهزة...",
    selectLanguage: "اختر لغتك",
    premiumCustomization: "تخصيص الروح المميز",
    alignment: "المحاذاة",
    position: "الموقع",
    typography: "الخطوط",
    styleAtmosphere: "جو الروح",
    styleMinimal: "بسيط",
    styleNature: "طبيعة",
    styleCalm: "هادئ",
    styleWarm: "دافئ",
    styleDeep: "عميق",
    styleLuxury: "فاخر",
    styleCreative: "إبداعي",
    fontModern: "عصري",
    fontPremium: "مميز",
    fontTech: "تقني",
    fontBold: "عريض",
    fontElegant: "أنيق",
    chooseLanguage: "اختر لغتك",
    selectLanguageSub: "اختر لغتك المفضلة للمتابعة",
    notificationMood: "شيء لروحك...",
    notificationFavorites: "جاهز لمزيد من الحكمة مثل مفضلاتك؟",
    copyText: "نسخ الحكمة",
    onboardingTitle1: "مرحباً بك في FeelSync",
    onboardingSub1: "رفيقك اليومي لتوازن الروح والحكمة.",
    onboardingTitle2: "بصيرة الروح",
    onboardingSub2:
      "تحدث إلى حكمتك الداخلية للحصول على اقتباسات مخصصة بناءً على شعورك.",
    onboardingTitle3: "إلهام يومي",
    onboardingSub3: "احصل على حكمة مختارة بعناية كل صباح لتبدأ يومك بشكل صحيح.",
    getStarted: "ابدأ الرحلة",
    next: "التالي",
    skip: "تخطي",
    goPremium: "فتح Soul Pro",
    premiumTitle: "فتح الإمكانات الكاملة",
    premiumSub: "ادعم التطبيق واحصل على ميزات حصرية",
    premiumFeature1: "أنماط روح حصرية",
    premiumFeature2: "تجربة خالية من الإعلانات",
    premiumFeature3: "خطوط روح مميزة",
    premiumFeature4: "بصائر روح غير محدودة",
    upgradeNow: "ترقية الآن",
    restorePurchases: "استعادة المشتريات",
    settings: "الإعدادات",
    rateApp: "تقييم FeelSync",
    feedback: "إرسال ملاحظات",
    privacyPolicy: "سياسة الخصوصية",
    termsOfService: "شروط الخدمة",
    about: "حول FeelSync",
    version: "Version 1.0.0",
    shareApp: "مشاركة FeelSync",
  },
  am: {
    appName: "FeelSync",
    categories: "ምድቦች",
    exploreWisdom: "ጥበብን በተለያዩ ጭብጦች ያስሱ",
    soulInsight: "የነፍስ ግንዛቤ",
    moodPlaceholder: "ነፍስዎ ምን ይሰማታል? ያውሩኝ...",
    analyze: "ጥበብን ፈልግ",
    dailyQuote: "የዕለት ተዕለት ጥበብ",
    trending: "ታዋቂ ጥበብ",
    randomQuote: "የዘፈቀደ ጥበብ",
    copied: "ጥበብ በተሳካ ሁኔታ ተገልብጧል",
    generating: "ጥበብን በመፈለግ ላይ...",
    analyzing: "ነፍስዎን በማዳመጥ ላይ...",
    noQuotes: "ምንም ጥበብ አልተገኘም",
    favorites: "የተከበረ ጥበብ",
    back: "ተመለስ",
    generateMore: "ተጨማሪ ፈልግ",
    detectedEmotion: "የነፍስ ሁኔታ",
    personalizedForYou: "ለነፍስዎ የተበጀ",
    setAsWallpaper: "እንደ ነፍስ ልጣፍ አዘጋጅ",
    homeScreen: "የመጀመሪያ ገጽ",
    lockScreen: "የመቆለፊያ ገጽ",
    downloading: "ጥበብን በማዘጋጀት ላይ...",
    wallpaperSaved: "ጥበብ በጋለሪ ውስጥ ተቀምጧል",
    streak: "የጥበብ ተከታታይነት",
    offlineMode: "የነፍስ ከመስمر ውጭ ሁነታ",
    notifications: "የነፍስ ማስታወሻዎች",
    enableNotifications: "የዕለት ተዕለት ማስታወሻዎችን አግብር",
    notificationsEnabledMessage: "ማስታወሻዎች ነቅተዋል!",
    notificationsDeniedMessage: "እባክዎ በቅንብሮች ውስጥ ማሳወقيةዎችን ይፍቀዱ",
    newQuoteAvailable: "አዲስ የዕለት ተዕለት ጥበብ ይገኛል!",
    religiousWisdom: "ቅዱስ ጥበብ",
    dailyQuoteNotification: "የዛሬው የግል ጥበብዎ ዝግጁ ነው...",
    selectLanguage: "ቋንቋዎን ይምረጡ",
    premiumCustomization: "ፕሪሚየም የነፍስ ማበጃ",
    alignment: "አሰላለፍ",
    position: "ቦتا",
    typography: "ታይፖግራፊ",
    styleAtmosphere: "የነፍስ ድባብ",
    styleMinimal: "ቀላል",
    styleNature: "ተፈጥሮ",
    styleCalm: "ረጋ ያለ",
    styleWarm: "ሞቅ ያለ",
    styleDeep: "ጥልቅ",
    styleLuxury: "የቅንጦት",
    styleCreative: "ፈጠራ",
    fontModern: "ዘመናዊ",
    fontPremium: "ፕሪሚየም",
    fontTech: "ቴክኖሎጂ",
    fontBold: "ደማቅ",
    fontElegant: "ግርማ ሞገስ ያለው",
    chooseLanguage: "ቋንቋዎን ይምረጡ",
    selectLanguageSub: "ለመቀጠል የሚመርጡትን ቋንቋ ይምረጡ",
    notificationMood: "ለነፍስዎ የሚሆን ነገር...",
    notificationFavorites: "እንደ እርስዎ ተወዳጆች ተጨማሪ ጥበብ ለማግኘት ዝግጁ ነዎት?",
    copyText: "ጥበብን ቅዳ",
    onboardingTitle1: "ወደ FeelSync እንኳን ደህና መጡ",
    onboardingSub1: "ለነፍስ ሚዛን እና ጥበብ የዕለት ተዕለት ጓደኛዎ።",
    onboardingTitle2: "የነፍስ ግንዛቤ",
    onboardingSub2: "ተኩስ ወደ حكمትክ ለመድረስ እንደ ስሜትህ የግል ጥቅሶችን አግኝ።",
    onboardingTitle3: "የዕለት ተዕለት መነሳሳት",
    onboardingSub3: "ቀንዎን በትክክል ለመጀመር በየቀኑ ጠዋት የተመረጠ ጥበብን ያግኙ።",
    getStarted: "ጉዞውን ጀምር",
    next: "ቀጣይ",
    skip: "ዝለል",
    goPremium: "Soul Proን ይክፈቱ",
    premiumTitle: "ሙሉ አቅምን ይክፈቱ",
    premiumSub: "መተግበريውን ይደግፉ እና ልዩ ባህሪያትን ያግኙ",
    premiumFeature1: "ልዩ የነፍስ ቅጦች",
    premiumFeature2: "ከማስታወቂያ ነፃ ተሞክሮ",
    premiumFeature3: "ፕሪሚየም የነፍስ ታይፖግራፊ",
    premiumFeature4: "ያልተገደበ የነፍስ ግንዛቤዎች",
    upgradeNow: "አሁን ያሻሽሉ",
    restorePurchases: "ግዢዎችን ይመልሱ",
    settings: "ቅንብሮች",
    rateApp: "FeelSyncን ደረጃ ይስጡ",
    feedback: "አስተያየት ይላኩ",
    privacyPolicy: "የግል መረጃ ጥበቃ ፖሊሲ",
    termsOfService: "የአገልግሎት ውል",
    about: "ስለ FeelSync",
    version: "Version 1.0.0",
    shareApp: "FeelSyncን ያጋሩ",
  },
  om: {
    appName: "FeelSync",
    categories: "Ramaddiiwwan",
    exploreWisdom: "Dhimmoota adda addaa keessatti ogummaa sakatta'i",
    soulInsight: "Hubannoo Lubbuu",
    moodPlaceholder: "Lubbuun kee maaltu isatti dhagahama? Natti dubbadhu...",
    analyze: "Ogummaa Barbaadi",
    dailyQuote: "Ogummaa Guyyaa",
    trending: "Ogummaa Beekamaa",
    randomQuote: "Ogummaa Akkaataa Tasaa",
    copied: "Ogummaan milkaayinaan garagalfameera",
    generating: "Ogummaa barbaadaa jira...",
    analyzing: "Lubbuu kee dhaggeeffachaa jira...",
    noQuotes: "Ogummaan hin argamne",
    favorites: "Ogummaa Jaallatamaa",
    back: "Deebi'i",
    generateMore: "Dabalata Barbaadi",
    detectedEmotion: "Haala Lubbuu",
    personalizedForYou: "Lubbuu keetiif kan qophaa'e",
    setAsWallpaper: "Akka Wulpeepparii Lubbuutti Tolchi",
    homeScreen: "Fuula Jalqabaa",
    lockScreen: "Fuula Cufaa",
    downloading: "Ogummaa qopheessaa jira...",
    wallpaperSaved: "Ogummaan galmee keessatti olkaayameera",
    streak: "Walitti fufiinsa Ogummaa",
    offlineMode: "Haala Lubbuu Oflaayinii",
    notifications: "Yaadachiisa Lubbuu",
    enableNotifications: "Yaadachiisa Guyyaa Jalqabsiisi",
    notificationsEnabledMessage: "Yaadachiisni jalqabeera!",
    notificationsDeniedMessage:
      "Maaloo qindaa'ina keessatti beeksisa jalqabsiisi",
    newQuoteAvailable: "Ogummaan guyyaa haaraan jira!",
    religiousWisdom: "Ogummaa Qulqulluu",
    dailyQuoteNotification: "Ogummaan kee kan har'aa qophaa'eera...",
    selectLanguage: "Afaan kee filadhu",
    premiumCustomization: "Mijeeffannaa Lubbuu Priimiyeemii",
    alignment: "Hiriira",
    position: "Iddoo",
    typography: "Taayipoogiraafii",
    styleAtmosphere: "Haala Lubbuu",
    styleMinimal: "Salphaa",
    styleNature: "Uumama",
    styleCalm: "Tasgabbaa'aa",
    styleWarm: "Ho'aa",
    styleDeep: "Gad-fagoo",
    styleLuxury: "Qananii",
    styleCreative: "Kalaqa",
    fontModern: "Ammayyaa",
    fontPremium: "Priimiyeemii",
    fontTech: "Teeknoojii",
    fontBold: "Furdaa",
    fontElegant: "Bareedaa",
    chooseLanguage: "Afaan kee filadhu",
    selectLanguageSub: "Itti fufuuf afaan jaallattu filadhu",
    notificationMood: "Waan lubbuu keetiif ta'u...",
    notificationFavorites:
      "Ogummaa dabalataa akka jaallatamtoota keetiitti argachuuf qophiidhaa?",
    copyText: "Ogummaa Garagalchi",
    onboardingTitle1: "Baga Gara FeelSync nagaan dhuftan",
    onboardingSub1: "Madaallii lubbuu fi ogummaaf hiriyyaa kee guyyaa guyyaa.",
    onboardingTitle2: "Hubannoo Lubbuu",
    onboardingSub2:
      "Akka sitti dhagahamutti kootota dhuunfaa argachuuf ogummaa kee keessoo waliin dubbadhu.",
    onboardingTitle3: "Inspirashinii Guyyaa",
    onboardingSub3:
      "Guyyaa kee sirriitti jalqabuuf guyyaa guyyaan ganama ogummaa filatame argadhu.",
    getStarted: "Imala Jalqabi",
    next: "Itti aana",
    skip: "Irra darbi",
    goPremium: "Soul Pro Banadhu",
    premiumTitle: "Dandeettii Guutuu Banadhu",
    premiumSub: "Appii deeggaruun tajaajila addaa argadhu",
    premiumFeature1: "Haala Lubbuu Addaa",
    premiumFeature2: "Tajaajila Beeksisa Malee",
    premiumFeature3: "Taayipoogiraafii Lubbuu Priimiyeemii",
    premiumFeature4: "Hubannoo Lubbuu Daangaa Malee",
    upgradeNow: "Amma Haaromsi",
    restorePurchases: "Bittaa Deebisi",
    settings: "Qindaa'ina",
    rateApp: "FeelSync Sadarkaa Kenni",
    feedback: "Yaada Ergi",
    privacyPolicy: "Imaammata Dhuunfaa",
    termsOfService: "Waliigaltee Tajaajilaa",
    about: "Waa'ee FeelSync",
    version: "Version 1.0.0",
    shareApp: "FeelSync Hiru",
  },
  sw: {
    appName: "FeelSync",
    categories: "Kategoria",
    exploreWisdom: "Gundua hekima kupitia mada mbalimbali",
    soulInsight: "Bustani ya Nafsi",
    moodPlaceholder: "Nafsi yako inahisije? Zungumza nami...",
    analyze: "Tafuta Hekima",
    dailyQuote: "Hekima ya Leo",
    trending: "Hekima Inayovuma",
    randomQuote: "Hekima ya Nasibu",
    copied: "Hekima imenakiliwa kikamilifu",
    generating: "Tukitafuta hekima...",
    analyzing: "Tukiisikiliza nafsi yako...",
    noQuotes: "Hakuna hekima iliyopatikana",
    favorites: "Hekima Thamani",
    back: "Rudi",
    generateMore: "Tafuta Zaidi",
    detectedEmotion: "Hali ya Nafsi",
    personalizedForYou: "Imeandaliwa kwa ajili ya nafsi yako",
    setAsWallpaper: "Weka kama Karatasi ya Nafsi",
    homeScreen: "Skrini ya Nyumbani",
    lockScreen: "Skrini ya Kufunga",
    downloading: "Tukiandaa hekima...",
    wallpaperSaved: "Hekima imehifadhiwa kwenye ghala",
    streak: "Mfululizo wa Hekima",
    offlineMode: "Hali ya Nafsi Nje ya Mtandao",
    notifications: "Vikumbusho vya Nafsi",
    enableNotifications: "Washa vikumbusho vya kila siku",
    notificationsEnabledMessage: "Vikumbusho vimewashwa!",
    notificationsDeniedMessage: "Tafadhali washa arifa kwenye mipangilio",
    newQuoteAvailable: "Hekima mpya ya kila siku inapatikana!",
    religiousWisdom: "Hekima Takatifu",
    dailyQuoteNotification: "Hekima yako binafsi ya leo iko tayari...",
    selectLanguage: "Chagua lugha yako",
    premiumCustomization: "Uboreshaji wa Nafsi wa Premium",
    alignment: "Mpangilio",
    position: "Nafasi",
    typography: "Maandishi",
    styleAtmosphere: "Mazingira ya Nafsi",
    styleMinimal: "Rahisi",
    styleNature: "Asili",
    styleCalm: "Tulia",
    styleWarm: "Changamfu",
    styleDeep: "Kina",
    styleLuxury: "Anasa",
    styleCreative: "Ubunifu",
    fontModern: "Kisasa",
    fontPremium: "Bora",
    fontTech: "Teknolojia",
    fontBold: "Nene",
    fontElegant: "Kifahari",
    chooseLanguage: "Chagua lugha yako",
    selectLanguageSub: "Chagua lugha unayopendelea ili kuendelea",
    notificationMood: "Kitu kwa ajili ya nafsi yako...",
    notificationFavorites: "Tayari kwa hekima zaidi kama unavyopenda?",
    copyText: "Nakili Hekima",
    onboardingTitle1: "Karibu FeelSync",
    onboardingSub1: "Mwenzi wako wa kila siku wa usawa wa nafsi na hekima.",
    onboardingTitle2: "Bustani ya Nafsi",
    onboardingSub2:
      "Zungumza na hekima yako ya ndani ili kupata nukuu binafsi kulingana na unavyohisi.",
    onboardingTitle3: "Uvuvio wa Kila Siku",
    onboardingSub3:
      "Pata hekima iliyochaguliwa kila asubuhi ili kuanza siku yako vizuri.",
    getStarted: "Anza Safari",
    next: "Inayofuata",
    skip: "Ruka",
    goPremium: "Fungua Soul Pro",
    premiumTitle: "Fungua Uwezo Kamili",
    premiumSub: "Saidia programu na ufurahie vipengele vya kipekee",
    premiumFeature1: "Mitindo ya Nafsi ya Kipekee",
    premiumFeature2: "Uzoefu Bila Matangazo",
    premiumFeature3: "Maandishi ya Nafsi ya Premium",
    premiumFeature4: "Bustani za Nafsi zisizo na Kikomo",
    upgradeNow: "Boresha Sasa",
    restorePurchases: "Rejesha Manunuzi",
    settings: "Mipangilio",
    rateApp: "Kadiria FeelSync",
    feedback: "Tuma Maoni",
    privacyPolicy: "Sera ya Faragha",
    termsOfService: "Masharti ya Huduma",
    about: "Kuhusu FeelSync",
    version: "Version 1.0.0",
    shareApp: "Yabelana nge-FeelSync",
  },
  zu: {
    appName: "FeelSync",
    categories: "Izigaba",
    exploreWisdom: "Hlola ukuhlakanipha ngezihloko ezahlukahlukene",
    soulInsight: "Ukukhanya Komphefumulo",
    moodPlaceholder: "Umphefumulo wakho uzizwa kanjani? Khuluma nami...",
    analyze: "Funa Ukuhlakanipha",
    dailyQuote: "Ukuhlakanipha Kanamhlanje",
    trending: "Ukuhlakanipha Okudumile",
    randomQuote: "Ukuhlakanipha Okungahleliwe",
    copied: "Ukuhlakanipha kukopishwe ngempumelelo",
    generating: "Sifuna ukuhlakanipha...",
    analyzing: "Silalela umphefumulo wakho...",
    noQuotes: "Abukho ukuhlakanipha okutholakele",
    favorites: "Ukuhlakanipha Okuyigugu",
    back: "Buyela emuva",
    generateMore: "Funa Okwengeziwe",
    detectedEmotion: "Isimo Somphefumulo",
    personalizedForYou: "Kwenzelwe umphefumulo wakho",
    setAsWallpaper: "Setha njenge-Wallpaper Yomphefumulo",
    homeScreen: "Isikrini Sasekhaya",
    lockScreen: "Isikrini Sokukhiya",
    downloading: "Silungiselela ukuhlakanipha...",
    wallpaperSaved: "Ukuhlakanipha kulondolozwe kugalari",
    streak: "Uchungechunge Lokuhlakanipha",
    offlineMode: "Imodi Yomphefumulo Engaxhunyiwe",
    notifications: "Izikhumbuzo Zomphefumulo",
    enableNotifications: "Vula izikhumbuzo zansuku zonke",
    notificationsEnabledMessage: "Izikhumbuzo zivuliwe!",
    notificationsDeniedMessage: "Sicela uvule izaziso kuzilungiselelo",
    newQuoteAvailable: "Ukuhlakanipha okusha kwansuku zonke kuyatholakala!",
    religiousWisdom: "Ukuhlakanipha Okungcwele",
    dailyQuoteNotification: "Ukuhlakanipha kwakho kwanamuhla sekulungile...",
    selectLanguage: "Khetha ulimi lwakho",
    premiumCustomization: "Ukwenza Ngokwezifiso Komphefumulo",
    alignment: "Ukuvumelanisa",
    position: "Indawo",
    typography: "Imibhalo",
    styleAtmosphere: "Isimo Somphefumulo",
    styleMinimal: "Okulula",
    styleNature: "Imvelo",
    styleCalm: "Okuzolile",
    styleWarm: "Okufudumele",
    styleDeep: "Okujulile",
    styleLuxury: "Okunethezekile",
    styleCreative: "Okunobuchule",
    fontModern: "Okwesimanje",
    fontPremium: "Okusezingeni",
    fontTech: "Okwetheknoloji",
    fontBold: "Okugqamile",
    fontElegant: "Okunobuhle",
    chooseLanguage: "Khetha ulimi lwakho",
    selectLanguageSub: "Khetha ulimi oluthandayo ukuze uqhubeke",
    notificationMood: "Okuthile komphefumulo wakho...",
    notificationFavorites:
      "Usukulungele ukuhlakanipha okwengeziwe njengezintandokazi zakho?",
    copyText: "Kopisha Ukuhlakanipha",
    onboardingTitle1: "Siyakwamukela ku-FeelSync",
    onboardingSub1:
      "Umngane wakho wansuku zonke wokulinganisela komphefumulo nokuhlakanipha.",
    onboardingTitle2: "Ukukhanya Komphefumulo",
    onboardingSub2:
      "Khuluma nokuhlakanipha kwakho kwangaphakathi ukuze uthole izingcaphuno ezenzelwe wena ngokusekelwe ekutheni uzizwa kanjani.",
    onboardingTitle3: "Ugqozi Lwansuku Zonke",
    onboardingSub3:
      "Thola ukuhlakanipha okukhethiwe njalo ekuseni ukuze uqale usuku lwakho kahle.",
    getStarted: "Qala Uhambo",
    next: "Okulandelayo",
    skip: "Yeqa",
    goPremium: "Vula i-Soul Pro",
    premiumTitle: "Vula Amandla Agcwele",
    premiumSub: "Sekela uhlelo lokusebenza futhi ujabulele izici ezikhethekile",
    premiumFeature1: "Izitayela Zomphefumulo Ezikhethekile",
    premiumFeature2: "Isipiliyoni Esingenazo Izikhangiso",
    premiumFeature3: "Imibhalo Yomphefumulo Ye-Premium",
    premiumFeature4: "Ukukhanya Komphefumulo Okungapheli",
    upgradeNow: "Thuthukisa Manje",
    restorePurchases: "Buyisela Okuthengiwe",
    settings: "Izilungiselelo",
    rateApp: "Linganisa i-FeelSync",
    feedback: "Thumela Impendulo",
    privacyPolicy: "Inqubomgomo Yobumfihlo",
    termsOfService: "Imigomo Yesevisi",
    about: "Mayelana ne-FeelSync",
    version: "Version 1.0.0",
    shareApp: "Yabelana nge-FeelSync",
  },
};

export const CATEGORIES: Category[] = [
  {
    id: "love",
    name: {
      en: "Love",
      fr: "Amour",
      es: "Amor",
      de: "Liebe",
      pt: "Amor",
      hi: "प्रेम",
      ar: "الحب",
      am: "ፍቅር",
      om: "Jaalala",
      sw: "Upendo",
      zu: "Uthando",
    },
    description: {
      en: "Affection and bonding",
      fr: "Affection et lien",
      es: "Afecto y unión",
      de: "Zuneigung und Bindung",
      pt: "Afeto e união",
      hi: "स्नेह और बंधन",
      ar: "المودة والترابط",
      am: "ፍቅር እና ትስስር",
      om: "Jaalala fi hidhata",
      sw: "Upendo na uhusiano",
      zu: "Uthando nobudlelwano",
    },
    icon: "Heart",
    abstractMeaning: {
      en: "The essence of affection and bonding.",
      fr: "L'essence de l'affection et du lien.",
      es: "La esencia del afecto y la unión.",
      de: "Die Essenz von Zuneigung und Bindung.",
      pt: "A essência do afeto e da união.",
      hi: "स्नेह और बंधन का सार।",
      ar: "جوهر المودة والترابط.",
      am: "የፍቅር እና የትስስር ምንነት።",
      om: "Bu’uura jaalala fi hidhata.",
      sw: "Kiini cha upendo na uhusiano.",
      zu: "Unyombo lothando nobudlelwano.",
    },
  },
  {
    id: "sadness",
    name: {
      en: "Sad",
      fr: "Triste",
      es: "Triste",
      de: "Traurig",
      pt: "Triste",
      hi: "उदास",
      ar: "حزين",
      am: "ሀዘን",
      om: "Gadda",
      sw: "Huzuni",
      zu: "Ukudabuka",
    },
    description: {
      en: "Healing and reflection",
      fr: "Guérison et réflexion",
      es: "Sanación y reflexión",
      de: "Heilung und Reflexion",
      pt: "Cura e reflexão",
      hi: "उपचार और प्रतिबिंब",
      ar: "الشفاء والتأمل",
      am: "ፈውስ እና ነጸብራቅ",
      om: "Fayyuu fi xiinxala",
      sw: "Uponyaji na kutafakari",
      zu: "Ukuphulukisa nokuzindla",
    },
    icon: "CloudRain",
    abstractMeaning: {
      en: "The path to healing and reflection.",
      fr: "Le chemin de la guérison et de la réflexion.",
      es: "El camino hacia la sanación y la reflexión.",
      de: "Der Weg zur Heilung und Reflexion.",
      pt: "O caminho para a cura e reflexão.",
      hi: "उपचार और प्रतिबिंब का मार्ग।",
      ar: "طريق الشفاء والتأمل.",
      am: "ወደ ፈውስ እና ነጸብራቅ የሚወስደው መንገድ።",
      om: "Karaa fayyuu fi xiinxala.",
      sw: "Njia ya uponyaji na kutafakari.",
      zu: "Indlela yokuphulukisa nokuzindla.",
    },
  },
  {
    id: "motivation",
    name: {
      en: "Motivation",
      fr: "Motivation",
      es: "Motivación",
      de: "Motivation",
      pt: "Motivação",
      hi: "प्रेरणा",
      ar: "تحفيز",
      am: "ተነሳሽነት",
      om: "Kaka’umsa",
      sw: "Motisha",
      zu: "Ugqozi",
    },
    description: {
      en: "Energy and drive",
      fr: "Énergie et entraînement",
      es: "Energía e impulso",
      de: "Energie und Antrieb",
      pt: "Energia e impulso",
      hi: "ऊर्जा और ड्राइव",
      ar: "الطاقة والدافع",
      am: "ጉልበት እና ተነሳሽነት",
      om: "Annisaa fi kaka’umsa",
      sw: "Nishati na nguvu",
      zu: "Amandla nogqozi",
    },
    icon: "Zap",
    abstractMeaning: {
      en: "The spark that ignites action and persistence.",
      fr: "L'étincelle qui déclenche l'action et la persévérance.",
      es: "La chispa que enciende la acción y la persistencia.",
      de: "Der Funke, der Handeln und Ausdauer entfacht.",
      pt: "A faísca que inflama a ação e a persistência.",
      hi: "वह चिंगारी जो क्रिया और दृढ़ता को प्रज्वलित करती है।",
      ar: "الشرارة التي تشعل العمل والمثابرة.",
      am: "ድርጊትን እና ጽናትን የሚያቀጣጥል ብልጭታ።",
      om: "Billaqa gochaa fi obsa kakaasu.",
      sw: "Cheche inayowasha hatua na uvumilivu.",
      zu: "Inhlansi evusa isenzo nokuphikelela.",
    },
  },
  {
    id: "success",
    name: {
      en: "Success",
      fr: "Succès",
      es: "Éxito",
      de: "Erfolg",
      pt: "Sucesso",
      hi: "सफलता",
      ar: "نجاح",
      am: "ስኬት",
      om: "Milkaa’ina",
      sw: "Mafanikio",
      zu: "Impumelelo",
    },
    description: {
      en: "Growth, achievement, ambition",
      fr: "Croissance, réussite, ambition",
      es: "Crecimiento, logro, ambición",
      de: "Wachstum, Leistung, Ehrgeiz",
      pt: "Crescimento, conquista, ambição",
      hi: "विकास, उपलब्धि, महत्वाकांक्षा",
      ar: "النمو والإنجاز والطموح",
      am: "እድገት፣ ስኬት፣ ምኞት",
      om: "Guddina, milkaa’ina, hawwii",
      sw: "Ukuaji, mafanikio, tamaa",
      zu: "Ukukhula, impumelelo, isifiso",
    },
    icon: "Trophy",
    abstractMeaning: {
      en: "The realization of goals and personal growth.",
      fr: "La réalisation des objectifs et la croissance personnelle.",
      es: "La realización de metas y el crecimiento personal.",
      de: "Die Verwirklichung von Zielen und persönliches Wachstum.",
      pt: "A realização de objetivos e crescimento pessoal.",
      hi: "लक्ष्यों की प्राप्ति और व्यक्तिगत विकास।",
      ar: "تحقيق الأهداف والنمو الشخصي.",
      am: "የግብ እና የግል እድገት እውን መሆን።",
      om: "Galma gahuu fi guddina dhuunfaa.",
      sw: "Utimilifu wa malengo na ukuaji wa kibinafsi.",
      zu: "Ukufezeka kwezinjongo nokukhula komuntu.",
    },
  },
  {
    id: "life",
    name: {
      en: "Life",
      fr: "Vie",
      es: "Vida",
      de: "Leben",
      pt: "Vida",
      hi: "जीवन",
      ar: "حياة",
      am: "ህይወት",
      om: "Jireenya",
      sw: "Maisha",
      zu: "Impilo",
    },
    description: {
      en: "Journey, experience, existence",
      fr: "Voyage, expérience, existence",
      es: "Viaje, experiencia, existencia",
      de: "Reise, Erfahrung, Existenz",
      pt: "Jornada, experiência, existência",
      hi: "यात्रा, अनुभव, अस्तित्व",
      ar: "الرحلة والخبرة والوجود",
      am: "ጉዞ፣ ልምድ፣ ህልውና",
      om: "Adeemsa, muuxannoo, jireenya",
      sw: "Safari, uzoefu, uwepo",
      zu: "Uhambo, isipiliyoni, ubukhona",
    },
    icon: "Compass",
    abstractMeaning: {
      en: "The continuous journey of learning and being.",
      fr: "Le voyage continu d'apprentissage et d'être.",
      es: "El viaje continuo de aprender y ser.",
      de: "Die kontinuierliche Reise des Lernens und Seins.",
      pt: "A jornada contínua de aprendizado e ser.",
      hi: "सीखने और होने की निरंतर यात्रा।",
      ar: "رحلة مستمرة من التعلم والوجود.",
      am: "ቀጣይነት ያለው የመማር እና የመሆን ጉዞ።",
      om: "Adeemsa barachuu fi jiraachuu itti fufiinsa qabu.",
      sw: "Safari inayoendelea ya kujifunza na kuwepo.",
      zu: "Uhambo oluqhubekayo lokufunda nokuba khona.",
    },
  },
  {
    id: "friendship",
    name: {
      en: "Friendship",
      fr: "Amitié",
      es: "Amistad",
      de: "Freundschaft",
      pt: "Amizade",
      hi: "मित्रता",
      ar: "صداقة",
      am: "ጓደኝነት",
      om: "Michummaa",
      sw: "Urafiki",
      zu: "Ubungane",
    },
    description: {
      en: "Loyalty, support, companionship",
      fr: "Loyauté, soutien, camaraderie",
      es: "Lealtad, apoyo, compañerismo",
      de: "Loyalität, Unterstützung, Kameradschaft",
      pt: "Lealdade, apoio, companheirismo",
      hi: "वफादारी, समर्थन, साथ",
      ar: "الولاء والدعم والرفقة",
      am: "ታማኝነት፣ ድጋፍ፣ ጓደኝነት",
      om: "Amanamummaa, deeggarsa, hiriyyummaa",
      sw: "Uaminifu, msaada, urafiki",
      zu: "Ubuqotho, ukusekelwa, ubungane",
    },
    icon: "Users",
    abstractMeaning: {
      en: "The bond of mutual trust and support.",
      fr: "Le lien de confiance et de soutien mutuel.",
      es: "El vínculo de confianza y apoyo mutuo.",
      de: "Die Bindung des gegenseitigen Vertrauens und der Unterstützung.",
      pt: "O vínculo de confiança e apoio mútuo.",
      hi: "पारस्परिक विश्वास और समर्थन का बंधन।",
      ar: "رابطة الثقة المتبادلة والدعم.",
      am: "የጋራ መተማመን እና የድጋፍ ትስስር።",
      om: "Waliin amanamummaa fi deeggarsa.",
      sw: "Uhusiano wa kuaminiana na kusaidiana.",
      zu: "Isibopho sokwethembana nokusekelana.",
    },
  },
  {
    id: "bible",
    name: {
      en: "Bible Quotes",
      fr: "Citations Bibliques",
      es: "Citas Bíblicas",
      de: "Bibelzitate",
      pt: "Citações Bíblicas",
      hi: "बाइबल के विचार",
      ar: "اقتباسات من الكتاب المقدس",
      am: "የመጽሐፍ ቅዱስ ጥቅሶች",
      om: "Caqasoota Kitaaba Qulqulluu",
      sw: "Nukuu za Biblia",
      zu: "Izingcaphuno zeBhayibheli",
    },
    description: {
      en: "Faith, wisdom, scripture",
      fr: "Foi, sagesse, écriture",
      es: "Fe, sabiduría, escritura",
      de: "Glaube, Weisheit, Schrift",
      pt: "Fé, sabedoria, escritura",
      hi: "विश्वास, ज्ञान, शास्त्र",
      ar: "الإيمان والحكمة والكتاب المقدس",
      am: "እምነት፣ ጥበብ፣ ቅዱሳት መጻሕፍት",
      om: "Amantii, ogummaa, barreeffama qulqulluu",
      sw: "Imani, hekima, maandiko",
      zu: "Ukholo, ukuhlakanipha, umbhalo",
    },
    icon: "BookOpen",
    abstractMeaning: {
      en: "Spiritual guidance through sacred texts.",
      fr: "Guidance spirituelle à travers les textes sacrés.",
      es: "Guía espiritual a través de textos sagrados.",
      de: "Spirituelle Führung durch heilige Texte.",
      pt: "Orientação espiritual através de textos sagrados.",
      hi: "पवित्र ग्रंथों के माध्यम से आध्यात्मिक मार्गदर्शन।",
      ar: "الإرشاد الروحي من خلال النصوص المقدسة.",
      am: "በቅዱሳት መጻሕፍት በኩል መንፈሳዊ መመሪያ።",
      om: "Qajeelfama hafuuraa barreeffama qulqulluutiin.",
      sw: "Mwongozo wa kiroho kupitia maandiko matakatifu.",
      zu: "Isiqondiso esingokomoya ngemibhalo engcwele.",
    },
  },
  {
    id: "quran",
    name: {
      en: "Quran Quotes",
      fr: "Citations du Coran",
      es: "Citas del Corán",
      de: "Koran-Zitate",
      pt: "Citações do Alcorão",
      hi: "कुरान के विचार",
      ar: "اقتباسات من القرآن",
      am: "የቁርኣን ጥቅሶች",
      om: "Caqasoota Qur’aanaa",
      sw: "Nukuu za Quran",
      zu: "Izingcaphuno zeQuran",
    },
    description: {
      en: "Peace, guidance, revelation",
      fr: "Paix, guidance, révélation",
      es: "Paz, guía, revelación",
      de: "Frieden, Führung, Offenbarung",
      pt: "Paz, orientação, revelação",
      hi: "शांति, मार्गदर्शन, रहस्योद्घाटन",
      ar: "السلام والهدى والوحي",
      am: "ሰላም፣ መመሪያ፣ መገለጥ",
      om: "Nagaa, qajeelfama, mul’ata",
      sw: "Amani, mwongozo, ufunuo",
      zu: "Ukuthula, isiqondiso, isambulo",
    },
    icon: "Moon",
    abstractMeaning: {
      en: "Divine wisdom and inner peace.",
      fr: "Sagesse divine et paix intérieure.",
      es: "Sabiduría divina y paz interior.",
      de: "Göttliche Weisheit und innerer Frieden.",
      pt: "Sabedoria divina e paz interior.",
      hi: "दिव्य ज्ञान और आंतरिक शांति।",
      ar: "الحكمة الإلهية والسلام الداخلي.",
      am: "መለኮታዊ ጥበብ እና ውስጣዊ ሰላም።",
      om: "Ogummaa Waaqaa fi nagaa keessaa.",
      sw: "Hekima ya kimungu na amani ya ndani.",
      zu: "Ukuhlakanipha kwaphezulu nokuthula kwangaphakathi.",
    },
  },
];
